OPEN-ENT-NG/magneto

- src/main/resources/public/template/board-read.html
Added the label in the clickable area with the arrow to unroll the select.
You can go on "Magneto" module --> Create a table (with sections) --> Have at least 2 sections --> And at least 1 magnet per section --> click on "Lecture" --> You should be able to click on the whole label + arrow to unroll the select.
[MAG-159](https://jira.support-ent.fr/browse/MAG-159)
> fix(boardRead): #MAG-159 unroll the select when clicking on the label

- src/main/resources/public/template/board-read.html
- src/main/resources/public/ts/controllers/board-read.controller.ts
Add safeApply in asychronous call to fix arrow display when there is only one card in board-read.
Module "Magneto" --> Create or open a board --> you need to have only one card --> button "Lecture" --> no arrow should be displayed
[MAG-172](https://jira.support-ent.fr/browse/MAG-172)
> fix(boardRead): #MAG-172 don't display arrow for one card

- src/main/resources/public/ts/controllers/board-read.controller.ts
Destroy keydown event to prevent error after initialising it and use it in board read.
Module "Magneto" --> Create or open a board --> you need to have at least two cards --> button "Lecture" --> user nav arrow to switch cards --> button "Retour" --> try to use nav arrow, nothing should happen.
[MAG-174](https://jira.support-ent.fr/browse/MAG-174)
> fix(boardRead): #MAG-174 fix error on nav arrow in board read

- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/es.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/containers/_board.scss
- src/main/resources/public/sass/global/components/directives/_board-description-lightbox.scss
- src/main/resources/public/sass/global/components/directives/_index.scss
- src/main/resources/public/template/board.html
- src/main/resources/public/ts/controllers/board-view.controller.ts
- src/main/resources/public/ts/directives/board-description-lightbox/board-description-lightbox.directive.ts
- src/main/resources/public/ts/directives/board-description-lightbox/board-description-lightbox.html
- src/main/resources/public/ts/directives/index.ts
When a board description is longer than 3 lines, "Read more" appear, on click open popup to display description in full length.
Go to "Magento" --> open a board --> add a description, test a small description (nothing append), then a long one ("Read more" appear), click on it and you should see a popup with the description.
[MAG-213](https://jira.support-ent.fr/browse/MAG-213)
> feat(boardView): #MAG-213 add lightbox to display long description

- src/main/java/fr/cgi/magneto/controller/BoardController.java
- src/main/java/fr/cgi/magneto/controller/FakeRight.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/core/constants/Rights.java
- src/main/java/fr/cgi/magneto/model/boards/BoardPayload.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/es.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/jsonschema/board.json
- src/main/resources/jsonschema/boardUpdate.json
- src/main/resources/public/sass/global/components/directives/_board-manage-lightbox.scss
- src/main/resources/public/ts/controllers/__test__/board-read.controller.test.ts
- src/main/resources/public/ts/directives/board-manage-lightbox/board-manage-lightbox.directive.ts
- src/main/resources/public/ts/directives/board-manage-lightbox/board-manage-lightbox.html
- src/main/resources/public/ts/magnetoBehaviours.ts
- src/main/resources/public/ts/models/__test__/board.model.test.ts
- src/main/resources/public/ts/models/board.model.ts
- src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
Added an option in board properties to display the number of favorites of a cards or not.
Also adde da workflow Right related to that "magneto.board.favorites"
Without the workflow right  "magneto.board.favorites", create a board, the checkbox for this option should not be displayed.
Then with the right create a board and check if the checkbox is here. If its here check it, then go to the board properties and verify if its still checked.
[MAG-218](https://jira.support-ent.fr/browse/MAG-218)
> feat(favorite): #MAG-218 add option in board property to display number of favorites per cards or not

- src/main/resources/public/template/board.html
- src/main/resources/public/ts/directives/board-description-lightbox/board-description-lightbox.directive.ts
When a board description is longer than 3 lines, "Read more" appear, on click open popup to display description in full length.
Go to "Magento" --> open a board --> add a description, test a small description (nothing append), then a long one ("Read more" appear), click on it and you should see a popup with the description.
[MAG-213](https://jira.support-ent.fr/browse/MAG-213)
> feat(boardView): #MAG-213 add lightbox to display long description #17

- src/main/resources/public/sass/global/components/directives/_card-list-item-options.scss
Add missing z-index to display card options properly.
Magneto module --> select a board --> open card options and you should see it properly (not under image preview/ vidéo or text)
[MAG-226](https://jira.support-ent.fr/browse/MAG-226)
> fix(css): #MAG-226 fix missing z-index for cards options

- src/main/resources/public/sass/global/components/containers/_board.scss
Shrink space in board description between description and "Lire plus" link to open popup when description is too long.
Go to Magneto --> Open a board with a long description --> resize the window to have mobile view.
[MAG-213](https://jira.support-ent.fr/browse/MAG-213)
> fix(boardDesc): #MAG-213 shrink space in board description

- src/main/java/fr/cgi/magneto/controller/BoardController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
- added `allFolders` parameter for fetching user boards regardless of the folder they're in.
Updated API documentation : 
https://confluence.support-ent.fr/display/RN/Boards
- check if users is still fetching all boards as previously
- check if adding the `allFolders` parameter in the GET /boards API allows fetching all boards from user
https://jira.support-ent.fr/browse/MAG-228
> feat(boards): #MAG-228 add option to fetch boards from all folders

- src/main/resources/public/ts/directives/section-list/section-list-item.directive.ts
- apply refresh of card positions when scrolling in a single section
- scroll on a section with more than 30 cards and verify if cards are not overlapping
https://jira.support-ent.fr/browse/MAG-241
> fix(sections): #MAG-241 refresh card positions when scrolling in sections

- src/main/resources/public/template/board-read.html
- src/main/resources/public/template/board.html
- src/main/resources/public/ts/directives/card-display/card-display.directive.ts
- src/main/resources/public/ts/directives/card-display/card-display.html
- src/main/resources/public/ts/directives/card-list/card-preview-image.directive.ts
- src/main/resources/public/ts/directives/card-list/card-preview-image.html
- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.html
- src/main/resources/public/ts/directives/card-preview-lightbox/card-preview-lightbox.directive.ts
- src/main/resources/public/ts/directives/card-preview-lightbox/card-preview-lightbox.html
- src/main/resources/public/ts/directives/file-viewer/file-viewer.directive.ts
- display "Download" and "Edit" buttons in file viewer only if the user has the rights (through sharing)
- share a board to a user
- if the user has "read" right, no button should be displayed
- if the user has the "reuse" right, the download button should be displayed"
- if the user has a "write" right, the "edit" button should be displayed
https://jira.support-ent.fr/browse/MAG-111
> fix(file-viewer): #MAG-111 display buttons only if the user has the proper rights

- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/model/Metadata.java
- src/test/java/fr/cgi/magneto/model/MetadataTest.java
fix documents which couldnt be opened with LibreOfficeOnline because of a missing extension.
Try to open a document with LibreOfficeOnline as lool provider.
[MAG-111](https://jira.support-ent.fr/browse/MAG-111)
> fix(board) : #MAG-111 fix documents which couldnt be opened with LibreOfficeOnline.

- src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/resources/i18n/timeline/de.json
- src/main/resources/i18n/timeline/en.json
- src/main/resources/i18n/timeline/es.json
- src/main/resources/i18n/timeline/fr.json
- src/main/resources/i18n/timeline/it.json
- src/main/resources/i18n/timeline/pt.json
- src/main/resources/view-src/notify/share_folder.html
fix notifications for share folders : 
- no longer notify the owner of the folder
- no longer notify with the boards notifications 
- improve folder notification (add title)
- Sharing a folder doesn't throw a notification to the owner
- Sharing a folder throw the correct folder notification with title 
> fix(notifications): #MAG-286  fix notifications

- src/main/java/fr/cgi/magneto/core/constants/Mongo.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
fix folders filter when getting boards : now doesn't return folderId if the user cant access the folder
Each boards return must be in their folder if the user has acces to said folder or be present in the main page without folderId
https://jira.support-ent.fr/browse/MAG-383
> fix(Boards): #MAG-383 fix get boards now handle board with one folder

- frontend/src/routes/app/index.tsx
add base blocks for module view
Check is the display indeed puts a tree view on the left and a card on the right (66% of the tree size in term of width)
[MAG-389](https://jira.support-ent.fr/browse/MAG-389)
> feat(react): #MAG-389 add base blocks for module view

- frontend/src/components/create-board/CreateBoard.tsx
- frontend/src/components/unique-image-picker/UniqueImagePicker.tsx
create-board style fixed
To resolve the initial issue where clicking on the drop zone of the second ImagePicker component placed the image in the first one, I encapsulated the component in a **wrapper (UniqueImagePicker) and used refs (wrapperRef, inputRef, idRef) to manage each instance uniquely**. 
I added event handlers to the document to check if the click occurred inside our specific component, avoiding redundant clicks.
> #MAG-353 resolve duplicate upload issue in multiple instances

- frontend/src/components/create-board/CreateBoard.tsx
boards are now created in currentFolder
> fix(Board) : #MAG-353 boards are created in the right folder

- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/core/enums/drag-and-drop-type.enum.ts
Fix highlighting of folder with subfolder when drag and dropping (it would highlight the entire section of the folder and its list of subfolders instead of just the folder)
Check if the highlights of the folders while DnDing are working properly on the treeview
[MAG-390](https://jira.support-ent.fr/browse/MAG-390)
> fix(treeview) : #MAG-390 fix highlighting of folder with subfolder

- frontend/src/components/toaster-container/ToasterContainer.tsx
fix open button not working (not implemented for boards, but working for folders)
Try to open folders with the "Open" button from the toaster
[MAG-355](https://jira.support-ent.fr/browse/MAG-355)
> fix(toaster) : #MAG-355 fix open button not working

- frontend/src/components/board-card/style.ts
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/magnets-collection/FavoriteViewByBoard.tsx
- frontend/src/components/magnets-collection/FavoriteViewByCard.tsx
- frontend/src/components/magnets-collection/style.ts
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
fix content not centered in favorites view
add LoadingScreen on loading a new board
Vérifier que les deux vues des favoris dans la page d'accueil fonctionnent correctement, notamment avec des tableaux à 1 ou 2 favoris seulement pour vérifier que l'alignement fonctionne bien.
[MAG-458](https://jira.support-ent.fr/browse/MAG-458)
> fix(favorite) : #MAG-458 add loading screen and fix content not centered in favorites view

- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
- backend/src/main/java/fr/cgi/magneto/model/boards/Board.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- backend/src/test/java/fr/cgi/magneto/model/BoardTest.java
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/cards-vertical-layout/style.ts
- frontend/src/components/section-name/SectionName.tsx
- frontend/src/components/section-name/style.ts
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
Fix the view being the same when having only the read rights as when having upper rights (read-only mode have no scrollbar, no creation section, no bullet menu, and can't interact with section names).
Il faut vérifier que la vue avec contrib ou + ne soit pas altérée et que la vue en read-only n'ait pas de scrollbar, pas de section de création, pas de bullet menu au niveau de la section et ne puisse pas intéragir avec les noms de sections.
[MAG-449](https://jira.support-ent.fr/browse/MAG-449)
> fix(boardview) : #MAG-449 fix read-only view missing

- frontend/src/components/Preview-modal/PreviewModal.tsx
- frontend/src/components/Preview-modal/style.ts
add arrows on preview to navigate between cards
Check any board types and card types, check if the buttons are there and if keyboard left and right arrow work.
[MAG-194](https://jira.support-ent.fr/browse/MAG-194)
> feat(preview) : #MAG-194 add arrows on preview to navigate between cards

- backend/src/main/java/fr/cgi/magneto/core/constants/Slideshow.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
Add description slide just after the title slide, with a "Description" title and the description text.
[MAG-544](https://jira.support-ent.fr/browse/MAG-544)
> feat(slideshow) : #MAG-544 add description slide

- backend/src/main/java/fr/cgi/magneto/core/enums/SlideResourceType.java
- backend/src/main/java/fr/cgi/magneto/factory/SlideFactory.java
- backend/src/main/java/fr/cgi/magneto/model/properties/SlideProperties.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideDescription.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideTitle.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
> fix(slide) : #MAG-545 fix description and title flow

- backend/pom.xml
This PR update the version of the parent pom to use to be able to deactivate jar minification which causes an error while exporting boards.
Before being accepted, the PR on edifice-parent needs to be accepted and the final version of app-parent fixed.
https://github.com/edificeio/edifice-parent/pull/3
> fix: #CGIDEV-284, deactivate jar minification

- frontend/src/components/tree-view/utils.ts
- frontend/src/providers/FoldersNavigationProvider/useInitialDeletedBoardsFolderObject.ts
- frontend/src/providers/FoldersNavigationProvider/useInitialMyBoardsFolderObject.ts
fix all initial folders having the same label when starting the main page (all folders are being "Tableaux de la plateforme)
Check on startup page if labels are now correct
[MAG-519](https://jira.support-ent.fr/browse/MAG-519)
> fix(treeview) : #MAG-519 fix all initial folders having the same label
