OPEN-ENT-NG/magneto

- src/main/resources/public/ts/controllers/board-view.controller.ts
Cards were duplicated when user open and save board properties without changing anything on layout free board.
Add a verification to avoid cards duplication.
Go to "magneto" module --> Open or create a board in free layout --> Create at least one card --> in the bottom left open settings --> save without change anything in settings. Cards should not be duplicate.
[MAG-178](https://jira.support-ent.fr/browse/MAG-178)
> fix(boardView): #MAG-178 fix cards duplication

- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/containers/_board.scss
- src/main/resources/public/sass/global/components/directives/_board-nav.scss
Modify css to have less white space on navigation bar and modify responsive behaviour.
Navbar on normal size screen:
Navbar on compressed window : 
Navbar normal mobile view : 
Navbar on compressed mobile view : 
Go on Magneto --> open a board --> resize the window to see behaviour of navbar.
[MAG-164](https://jira.support-ent.fr/browse/MAG-164)
> fix(boardNav): #MAG-164 fix responsive and spaces

- src/main/resources/public/sass/global/components/directives/_card-manage-lightbox.scss
- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.directive.ts
- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.html
You can now edit the link of a video card to change the attached video.
Try to create a new video card, double click on it and click on the edit button on the right of the preview. Change the video and check if the video has changed in the card
[MAG-163](https://jira.support-ent.fr/browse/MAG-163)
> feat(edit-video): #MAG-163 edit the link of a video card

- build.sh
- docker-compose.yml
Add parameter to buildNode command.
[MAG-215](https://jira.support-ent.fr/browse/MAG-215)
> chore: #MAG-215 fix yarn env build time

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/controller/StatisticController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/core/constants/Mongo.java
- src/main/java/fr/cgi/magneto/helper/DateHelper.java
- src/main/java/fr/cgi/magneto/helper/JsonHelper.java
- src/main/java/fr/cgi/magneto/model/statistics/StatisticsPayload.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/CardService.java
- src/main/java/fr/cgi/magneto/service/ServiceFactory.java
- src/main/java/fr/cgi/magneto/service/UserService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultSectionService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultUserService.java
- src/main/resources/jsonschema/statistics.json
Add a statistics endpoint thats gives board and cards created for a date by user
Check if you can use this endpoint only if you are superadmin
Check if you have access to the statistics for a day
[MAG-181](https://jira.support-ent.fr/browse/MAG-181)
> feat(statistics): #MAG-181 add statistics endpoint for zeppelin usage

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/helper/ImportExportHelper.java
- src/main/java/fr/cgi/magneto/service/impl/MagnetoRepositoryEvents.java
added import export support throught module mes données
Add some data in Magneto, then go to the "Mes Données" module, export data from Magneto, and try to import the file that the export provided. Check in the Magneto module if the data has been imported.
[MAG-43](https://jira.support-ent.fr/browse/MAG-43)
> feat(import/export): #MAG-43 Import export "mes données"

- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/_switch.scss
- src/main/resources/public/sass/global/components/_toasts.scss
- src/main/resources/public/sass/global/components/containers/_boards.scss
- src/main/resources/public/sass/global/components/directives/_board-list-folder.scss
- src/main/resources/public/sass/global/components/directives/_card-manage-lightbox.scss
- src/main/resources/public/sass/global/components/directives/_folder-tree-nav.scss
- src/main/resources/public/sass/global/components/directives/_search-bar.scss
- src/main/resources/public/sass/index.scss
Remove entcore-css-lib import, add local variable for color and replace it in scss.
Go to Magneot module and look if it look like before.
[MAG-226](https://jira.support-ent.fr/browse/MAG-226)
> fix(css): #MAG-226 remove entcore-css-lib import and add local variable

- src/main/java/fr/cgi/magneto/controller/BoardController.java
- src/main/java/fr/cgi/magneto/controller/CardController.java
- src/main/java/fr/cgi/magneto/controller/SectionController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/core/constants/Mongo.java
- src/main/java/fr/cgi/magneto/model/boards/Board.java
- src/main/java/fr/cgi/magneto/model/cards/Card.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/CardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/test/java/fr/cgi/magneto/model/BoardTest.java
- src/test/java/fr/cgi/magneto/model/CardTest.java
- src/test/java/fr/cgi/magneto/service/CardServiceTest.java
Updated endpoint that returns cards to add 2 fields:
- `hasLiked`: true if the user making the request has put into Favorite this card.
- `nbOfFavorites`: to count the total number of favorites among all the users.
Updated endpoint that returns boards to add 1 field:
- `displayNbFavorites`: to know if we show nb of like of cards from this board
Only the response change for the updated endpoints. 
Here is a list of endpoint that were updated:
CardController
- @Get("/cards/collection")
- @Get("/cards/:boardId")
- @Get("/cards/section/:sectionId")
- @Get("/card/:id")
BoardController
- @Post("/boards")
To test this feature, you need to be able to add a card to favorite. (with postman and [MAG-219](https://jira.support-ent.fr/browse/MAG-219) or with …
> feat(favorite): #MAG-220 Update existing endpoint for favorite implementation

- src/main/java/fr/cgi/magneto/controller/CardController.java
- src/main/java/fr/cgi/magneto/core/constants/Actions.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/core/constants/Rights.java
- src/main/java/fr/cgi/magneto/excpetion/BadRequestException.java
- src/main/java/fr/cgi/magneto/excpetion/MagnetoException.java
- src/main/java/fr/cgi/magneto/excpetion/RessourceNotFoundException.java
- src/main/java/fr/cgi/magneto/helper/HttpRequestHelper.java
- src/main/java/fr/cgi/magneto/model/cards/Card.java
- src/main/java/fr/cgi/magneto/model/cards/CardPayload.java
- src/main/java/fr/cgi/magneto/security/ReadBoardRight.java
- src/main/java/fr/cgi/magneto/service/CardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/resources/jsonschema/cardUpdateFavorite.json
- src/test/java/fr/cgi/magneto/model/CardPayloadTest.java
- src/test/java/fr/cgi/magneto/model/CardTest.java
I have created a new endpoint @Put("/card/favorite/:id") that allows changing the favorite status of a card for a user.
The card's id is included in the parameters, and the body of the request contains a boolean:
- true: it removes the user from the favorites list of this card.
- false: it adds the user to the favorites list of this card.
In addition, I have introduced a system to trigger custom exceptions that are used to return a specific status code to the user in case of a problem in the program.
This can be tested with Postman by sending requests to the endpoint @Put("/card/favorite/:id"). If the boolean is true and you're not on the favorite list, or if the boolean is false and you're already on the favorite list, an HTTP error 400 (Bad Request) will be returned. If the card id you …
> feat(favorite): #MAG-219 create card favorite endpoint

- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/es.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/public/ts/core/enums/resource-order.enum.ts
- src/main/resources/public/ts/directives/card-collection/card-collection.directive.ts
- src/main/resources/public/ts/directives/card-collection/card-collection.html
- src/test/java/fr/cgi/magneto/service/CardServiceTest.java
Add a feature allowing the user to order by favorite in card collection.
Use the toggle button in card collection to order by favorite, to see them in priority. You can do the same operation when you group by board.
[MAG-223](https://jira.support-ent.fr/browse/MAG-223)
> feat(favorite): #MAG-223 add sort by fav in card's collection

- src/main/resources/public/sass/global/components/containers/_board.scss
Add header no-1d css for theme-open-ent@3.1.0.
Go to magneto -> navigate in module -> verify header style
[MAG-226](https://jira.support-ent.fr/browse/MAG-226)
> fix(css): #MAG-226 fix missing css for specific theme version

- src/main/resources/public/sass/global/components/directives/_card-collection-lightbox.scss
Fix missing css class for card collection lightbox.
Go to Magneto --> Open a board --> open "aimant" collection
[MAG-226](https://jira.support-ent.fr/browse/MAG-226)
> fix(css): #MAG-226 fix missing css for card collection lightbox

- deployment/magneto/conf.json.template
- src/main/java/fr/cgi/magneto/config/MagnetoConfig.java
- src/main/java/fr/cgi/magneto/controller/CardController.java
- src/main/java/fr/cgi/magneto/controller/MagnetoController.java
- src/main/java/fr/cgi/magneto/controller/SectionController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/model/MongoQuery.java
- src/main/java/fr/cgi/magneto/model/cards/Card.java
- src/main/java/fr/cgi/magneto/service/CardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/resources/public/ts/controllers/board-view.controller.ts
- src/main/resources/public/ts/directives/card-list/card-list-item.directive.ts
- src/main/resources/public/ts/directives/card-list/card-list-item.html
- src/main/resources/public/ts/directives/favorite-button/favorite-button.directive.ts
- src/main/resources/public/ts/directives/favorite-button/favorite-button.html
- src/main/resources/public/ts/models/card.model.ts
- src/main/resources/public/ts/services/cards.service.ts
- src/main/resources/view-src/magneto.html
- src/test/java/fr/cgi/magneto/model/CardTest.java
- src/test/java/fr/cgi/magneto/service/CardServiceTest.java
Every x seconds the number of likes of all the cards of the opened board is refreshed.
new conf 
```
"magnetoUpdateFrequency": ${magnetoUpdateFrequency} //in milliseconds
```
The default refresh rate is set to 10 seconds. If the rate in the config is lower than this, then the refresh rate will be 10 seconds.
open the same board with 2 differents account (share it and open the other account in private navigation)
With one of the account add a card to favorite
Check with on the other account if the number of favorite has been updated (wait the refreshFrequency time set in conf)
[MAG-222](https://jira.support-ent.fr/browse/MAG-222)
> feat(favorite): #MAG-222 refresh number of favorites

- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/directives/_board-nav.scss
Modify navbar scss in a board to fit with description and have a responsive behaviour.
Go to Magneto --> open a board --> check the navbar behaviour.
[MAG-164](https://jira.support-ent.fr/browse/MAG-164)
> fix(navbar): #MAG-164 modify scss to fit description and responsive

- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.directive.ts
Add jquery code with coditions to retrieve values on card description when containing href or text.
Go to Magneto module --> open a board --> create a "text" card --> with editor, create a link --> save card
[MAG-162](https://jira.support-ent.fr/browse/MAG-162)
> fix(card): #MAG-162 add jquery to retrieve values on card description

- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/containers/_board.scss
- src/main/resources/public/sass/global/components/directives/_board-nav.scss
- src/main/resources/public/template/board.html
- src/main/resources/public/ts/directives/board-description-lightbox/board-description-lightbox.directive.ts
Modify css to have the best responsive behaviour for desktop, tablet and mobile.
Desktop view :
Tablet view :
Mobile view :
Go to "Magneto" --> open a board --> resize window.
[MAG-213](https://jira.support-ent.fr/browse/MAG-213)
> fix(boardDesc): #MAG-213 modify responsive behaviour for board description

- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/components/directives/_index.scss
- src/main/resources/public/sass/global/components/directives/_pdf-viewer.scss
- src/main/resources/public/ts/directives/card-list/card-preview-image.directive.ts
- src/main/resources/public/ts/directives/card-list/card-preview-image.html
- src/main/resources/public/ts/directives/index.ts
- src/main/resources/public/ts/directives/pdf-viewer/pdf-viewer.directive.new.ts
- src/main/resources/public/ts/directives/pdf-viewer/pdf-viewer.directive.ts
- src/main/resources/public/ts/directives/pdf-viewer/pdf-viewer.html
pdf viewer directive to display pdf from workspace 
https://jira.support-ent.fr/browse/MAG-190
> feat(Card-view) #MAG-190 : pdf viewer directive to display pdf

- src/main/resources/public/sass/global/components/directives/_section-list.scss
- src/main/resources/public/ts/controllers/board-view.controller.ts
- src/main/resources/public/ts/directives/section-list/section-list-item.directive.ts
- src/main/resources/public/ts/directives/section-list/section-list.html
Fixed a bug while dragging section, create section panel getting draged too
Drag section and see if there is no problem with the section which allows section creation
[MAG-156](https://jira.support-ent.fr/browse/MAG-156)
> fix(sections): #MAG-156 fix drag sections with create section swap

- src/main/resources/i18n/timeline/de.json
- src/main/resources/i18n/timeline/en.json
- src/main/resources/i18n/timeline/es.json
- src/main/resources/i18n/timeline/fr.json
- src/main/resources/i18n/timeline/it.json
- src/main/resources/i18n/timeline/pt.json
Add missing i18n key for external notifications.
Go to user profile --> Tab "Gérer mes notifications externes" --> Find "Magnéto" --> You should see "Partage d'un tableau".
[MAG-248](https://jira.support-ent.fr/browse/MAG-248)
> fix(i18n): #MAG-248 add missing i18n key in magneto timeline

- src/main/resources/public/ts/directives/board-list/board-list-item.html
- src/main/resources/public/ts/models/board.model.ts
adding tooltip on boards title
https://jira.support-ent.fr/browse/MAG-229
> fix(Board) #MAG-229 : doing tooltip on board title

- src/main/resources/public/sass/global/components/containers/_board.scss
- src/main/resources/public/sass/global/components/directives/_card-list.scss
- src/main/resources/public/sass/global/components/directives/_section-list.scss
- src/main/resources/public/template/board.html
- src/main/resources/public/ts/controllers/__test__/board-view.controller.test.ts
- src/main/resources/public/ts/controllers/board-view.controller.ts
- src/main/resources/public/ts/directives/section-list/section-list.html
Fixed the view to have a page without scroll, so all informations is visible instantaneously
Check if there is no scroll in section window
Check if you can access to all cards in vertical view while scrolling depending of screen
[MAG-209](https://jira.support-ent.fr/browse/MAG-209)
> fix(sections): #MAG-209 fix section scrolling view

- src/main/java/fr/cgi/magneto/config/MagnetoConfig.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultSectionService.java
- src/main/resources/public/sass/global/components/directives/_card-list.scss
- src/main/resources/public/ts/core/constants/video-platform.const.ts
- src/main/resources/public/ts/directives/card-list/card-list-item-preview.directive.ts
- src/main/resources/public/ts/directives/card-list/card-list-item-preview.html
- src/main/resources/public/ts/models/video-platform.model.ts
- src/main/resources/public/ts/services/video-platform.service.ts
Fixed perfs problem by replacing iframe by thumbnail
Check if all thumbnail is correctly loaded for all platforms (vimeo, youtube, dailymotion, peertube)
[MAG-241](https://jira.support-ent.fr/browse/MAG-241)
> fix(video): #MAG-241 add thumbnail for video's cards

- src/main/resources/public/sass/global/components/directives/_board-nav.scss
- make top offset for sidebar responsive with any screen sizes
- check if the sidebar is well placed with screens of any sizes
https://jira.support-ent.fr/browse/MAG-254
> fix(navbar): #MAG-254 fix responsive for side-bar

- src/main/resources/public/sass/global/components/directives/_pdf-viewer.scss
- src/main/resources/public/ts/directives/card-list/card-preview-image.html
- src/main/resources/public/ts/directives/pdf-viewer/pdf-viewer.directive.ts
- src/main/resources/public/ts/directives/pdf-viewer/pdf-viewer.html
- added responsive behaviour for PDF previews
- added filename on top of the PDF file
- added border around the PDF
- open a pdf file and check if it displays properly on all screen sizes
https://jira.support-ent.fr/browse/MAG-190
> fix(pdf-viewer): #MAG-190 added responsive for pdf + added filename

- src/main/resources/public/sass/global/components/containers/_boards.scss
- src/main/resources/public/ts/directives/card-collection/card-collection.directive.ts
- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.directive.ts
display file name by default when creating magnet with file 
https://jira.support-ent.fr/browse/MAG-192
> feat(CardManage) #MAG-192 : Display file name by default

- src/main/resources/public/ts/controllers/board-view.controller.ts
- src/main/resources/public/ts/directives/section-list/section-list-item.html
Fix drag&drop working on the whole section in vertical listing to only work on title. 
Check the drag&drop of both section and tickets, particulary from whole section and title only. ALso need to check on server like ng2 to ensure there's no DOM loading problems occuring.
[MAG-252](https://jira.support-ent.fr/browse/MAG-252)
> fix(board) : #MAG-252 : Fix drag&drop working on the whole section to only work on title.

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/resources/public/sass/global/components/directives/_card-list.scss
- src/main/resources/public/sass/global/components/directives/_section-list.scss
- src/test/java/fr/cgi/magneto/service/CommentServiceTest.java
fix scroll horizontal :  aimants sur une ligne avec un scroll horizontal
https://jira.support-ent.fr/browse/MAG-192
> feat(fileViewer) MAG-258 : scroll fix horizontal

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/controller/BoardAccessController.java
- src/main/java/fr/cgi/magneto/controller/BoardController.java
- src/main/java/fr/cgi/magneto/core/constants/CollectionsConstant.java
- src/main/java/fr/cgi/magneto/model/MongoQuery.java
- src/main/java/fr/cgi/magneto/model/boards/BoardAccess.java
- src/main/java/fr/cgi/magneto/service/BoardAccessService.java
- src/main/java/fr/cgi/magneto/service/ServiceFactory.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardAccessService.java
- src/test/java/fr/cgi/magneto/service/BoardAccessServiceTest.java
Add api to get boards acces by user
Add new test : testgetLastAccess
New API ("/board/view/last")
`{
"all": [
{
"title": "tgea",
"imageUrl": "/workspace/document/f6bfc34c-9888-4125-b055-b5a1c119dd48",
"backgroundUrl": null,
"description": null,
"shared": [],
"creationDate": null,
"modificationDate": "2023-10-26 07:37:46",
"folderId": null,
"layoutType": "vertical",
"deleted": false,
"ownerId": "4f4b2d62-75c9-4240-8201-19fe866e4290",
"public": false,
"layoutFree": false,
"ownerName": "Pic Marylou",
"cardsSection": [],
"id": "4bdfb8ea-51e9-42f0-87fb-b314797b5e98"
},
]
}`
https://jira.support-ent.fr/browse/MAG-257
> feat(Appli-Mobile) #MAG-257 : add new API to trace views on boards

- src/main/resources/public/ts/directives/file-viewer/file-viewer.directive.ts
- src/main/resources/public/ts/directives/file-viewer/file-viewer.html
Add editing button on lool compatible documents which opens them on your lool provider.
Go to a file magnet and test if the button is there when the document is lool compatible (doc, ppt or xls compatible) and if you have the "manage" right. Also test the button is properly redirecting to a new 
[MAG-111](https://jira.support-ent.fr/browse/MAG-111)
> feat(document) : #MAG-111 Add editing button on lool compatible documents which opens them on your lool provider.

- src/main/resources/public/ts/directives/file-viewer/file-viewer.directive.ts
fix function name to call correct API with excel
> fix(FileViewer): #MAG-203 fix preview blob

- src/main/resources/view-src/magneto.html
fix navbar by displaying a another navbar below it
https://jira.support-ent.fr/browse/MAG-235
> fix(CSS): #MAG-235 fix navbar by displaying a another navbar below it

- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.html
no longer display preview on creation
> fix(CardBoardManage): #MAG-203  no longer display preview on creation

- src/main/resources/public/ts/controllers/board-view.controller.ts
fix title for mp4 on drag and drop
> fix(CardBoardManage): #MAG-192 display mp4 title

- src/main/resources/public/sass/global/components/directives/_section-list.scss
Fix incorrect mouse icon when hovering non draggable elements.
Check mouse icon when hovering non draggable elements (must be normal) and draggable elements (must have the cross to move things around).
[MAG-252](https://jira.support-ent.fr/browse/MAG-252)
> fix(board) : #MAG-252 Fix incorrect mouse icon when hovering non draggable elements.

- src/main/java/fr/cgi/magneto/controller/SectionController.java
- src/main/java/fr/cgi/magneto/core/constants/Rights.java
- src/main/java/fr/cgi/magneto/security/ContribBoardRight.java
- if a section is hidden, only hide it if the shared user has only reading right (they can see the section if they have a contribution right)
- As the board manager hide a section
- Share the board to a user with read right
- Check if the user has access to the section (they should not)
https://jira.support-ent.fr/browse/MAG-191
> fix(sections): #MAG-191 hide section if user has read right only

- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
- src/main/resources/public/ts/directives/file-viewer/file-viewer.directive.ts
- change button color in file viewer
- increase preview width in popup
- check if previously mentioned changes are visible in a file preview
> fix(file-viewer): #MAG-203 change button color + preview width

- src/main/resources/public/ts/directives/file-viewer/file-viewer.directive.ts
Fix CSV preview not working.
Display details of a .csv file in Magneto and check if the preview is correct.
[MAG-203](https://jira.support-ent.fr/browse/MAG-203)
> fix(board) : #MAG-203 Fix CSV preview not working.

- src/main/java/fr/cgi/magneto/security/ContribBoardRight.java
- fix display sections with contrib right. The user has to have at least this share right to be able to see hidden sections.
- share a board with reading right: the user should not see the section
https://jira.support-ent.fr/browse/MAG-191
> fix(sections): #MAG-191 fix rights for ContribRight

- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
- src/main/resources/public/ts/directives/file-viewer/csv-viewer/csv-viewer.directive.ts
- src/main/resources/public/ts/directives/file-viewer/csv-viewer/csv-viewer.html
Refactoring navPage for excel  
-Check if navbar is present only if nbPage > 1 
-Check if navbar stay stick when scrolling  
> fix (FileViewer ) #MAG-203:  file viewer css navPage

- src/main/resources/public/sass/global/components/directives/_card-manage-lightbox.scss
- src/main/resources/public/sass/global/components/directives/_card-preview-image.scss
- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
- src/main/resources/public/sass/global/components/directives/_pdf-viewer.scss
- src/main/resources/public/ts/directives/file-viewer/csv-viewer/csv-viewer.directive.ts
- src/main/resources/public/ts/directives/file-viewer/file-viewer.directive.ts
- src/main/resources/public/ts/directives/file-viewer/file-viewer.html
Fix xlsx and pdf css on preview and update
> fix(FileViewer): #MAG-203 :fixing css for preview and update

- src/main/resources/public/sass/global/components/directives/_card-manage-lightbox.scss
- src/main/resources/public/sass/global/components/directives/_card-preview-image.scss
- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
- src/main/resources/public/ts/directives/file-viewer/file-viewer.html
fix css on preview and update again .
-Test with long csv to test scroll
-Test PDF
-Test img
-Test vidéo
> fix(file-viewer) #MAG-203 : fix css on preview and update

- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/public/sass/global/components/directives/_card-list-item-options.scss
- src/main/resources/public/ts/directives/card-list/card-list-item/card-list-item-options/card-list-item-options.html
- change option text for sections hiding/showing
- as a board owner, hide and/or show a section and check if the text is updated
https://jira.support-ent.fr/browse/MAG-191
> fix(sections): #MAG-191 update text for hiding sections

- src/main/resources/public/sass/global/components/directives/_section-list.scss
- src/main/resources/public/ts/directives/section-list/section-list-item.html
- src/main/resources/public/ts/directives/section-list/section-list.html
Fix cursor to show as default when not having the needed right.
Check if the cursor is the right one when using different rights (read/contrib and publish/manager)
[MAG-252](https://jira.support-ent.fr/browse/MAG-252)
> fix(board) : #MAG-252 Fix cursor to show as default when not having the needed right.

- src/main/resources/public/sass/global/components/directives/_card-list-item-options.scss
- src/main/resources/public/ts/directives/section-list/section-list-item.directive.ts
- src/main/resources/public/ts/directives/section-list/section-list-item.html
- src/main/resources/public/ts/directives/section-list/section-list.html
Fix menu not displaying the duplicate option with publish rights (and some size related stuff with this menu).
Droits lecture et réutilisation : pas de menu 
Droit écriture : menu avec que l'option dupliquer
Droit gestion : tout
[MAG-272](https://jira.support-ent.fr/browse/MAG-272)
> fix(board) : #MAG-272 Fix menu not displaying the duplicate option with publish rights (and some size related stuff with this menu).

- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.directive.ts
- src/main/resources/public/ts/directives/file-viewer/file-viewer.html
fix responsive with flex 
fix update title when opening card-manage: title is now the correct title and not the filename
> fix(FileViewer): #MAG-203 : remove override and fix responsive 

- README.md
- deployment/magneto/conf.json.template
- src/main/java/fr/cgi/magneto/config/MagnetoConfig.java
- src/main/java/fr/cgi/magneto/controller/MagnetoController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/es.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/directives/board-container-header-title/board-container-header-title.directive.ts
- src/main/resources/public/ts/directives/board-container-header-title/board-container-header-title.html
- src/main/resources/public/ts/directives/board-container-header/board-container-header.directive.ts
- src/main/resources/public/ts/directives/board-container-header/board-container-header.html
- src/main/resources/public/ts/directives/index.ts
- src/main/resources/view-src/magneto.html
If magneto is standalone title does not show module logo
- activate standalone config
- check title
[MAG-237](https://jira.support-ent.fr/browse/MAG-237)
> feat(standalone): #MAG-237 change display if standalone

- src/main/java/fr/cgi/magneto/controller/BoardAccessController.java
- src/main/java/fr/cgi/magneto/model/MongoQuery.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardAccessService.java
- src/test/java/fr/cgi/magneto/service/BoardAccessServiceTest.java
* fix sort in mongo by adding field in $group
* fix sort in java by keeping board order when calling boardService
* Must return 5 fields or less
* Boards must be returned in access order from more recent to less recent 
https://jira.support-ent.fr/browse/MAG-257
> fix(BoardAccess): #MAG-257 fix sort in mongo and java

- src/main/resources/public/sass/global/_magneto.scss
- src/main/resources/public/sass/global/components/containers/_board-read.scss
- src/main/resources/public/sass/global/components/directives/_card-display.scss
- src/main/resources/public/sass/global/components/directives/_card-preview-image.scss
- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
Updates images and buttons  of file viewer to be more responsive.
> fix(FileViewer): #MAG-203 updates images and buttons  of file viewer to be more responsive.

- src/main/resources/public/sass/global/components/directives/_card-preview-image.scss
img keep is ratio
https://jira.support-ent.fr/browse/MAG-283
> fix(img) #MAG-283 : fix resize img

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/controller/WorkspaceController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/core/constants/Rights.java
- src/main/java/fr/cgi/magneto/service/ServiceFactory.java
- src/main/java/fr/cgi/magneto/service/WorkspaceService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultWorkspaceService.java
- src/main/resources/public/ts/directives/file-viewer/file-viewer.directive.ts
- src/main/resources/public/ts/services/index.ts
- src/main/resources/public/ts/services/workspace.service.ts
- in the file viewer panel, display the "Edit" button only if the user owns the file or the user has the updateDocument share right
- give a user edition right to a file attached to a magnet
- check if the user has the edit button displayed
- remove the right and check again
https://jira.support-ent.fr/browse/MAG-111
> feat(file-viewer): #MAG-203 display update file button based on workspace edit right

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
- src/main/java/fr/cgi/magneto/core/constants/CollectionsConstant.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/core/constants/Rights.java
- src/main/java/fr/cgi/magneto/helper/WorkspaceHelper.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/CardService.java
- src/main/java/fr/cgi/magneto/service/WorkspaceService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultWorkspaceService.java
- src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.directive.ts
- src/main/resources/public/ts/directives/share-panel-lightbox/share-panel-lightbox.directive.ts
- src/main/resources/public/ts/directives/share-panel-lightbox/share-panel-lightbox.html
- src/main/resources/public/ts/services/boards.service.ts
- migrate the share file synchronization logic to backend for avoiding flooding by using the share API
- share a board as the owner : all the owner files in the board are shared to all the board users
- add a magnet as the owner : the file should be shared to all the board users, matching the board rights
- add a magnet as another user : the file should be shared as a readonly file to all users including the board owner
https://jira.support-ent.fr/browse/MAG-111
> fix(share): #MAG-111 migrate share doc process to backend

- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/es.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/public/sass/global/components/directives/_board-nav.scss
Updating i18n for video 
Make some more room in navbar with css
https://jira.support-ent.fr/browse/MAG-268
> fix(Navbar) #MAG-268 : new i18n for video with small css changes

- src/main/resources/public/sass/global/components/containers/_boards.scss
remove useless code wich broke the css
https://jira.support-ent.fr/browse/MAG-289
> fix(Boards) #MAG-289: aligns buttons in boards

- src/main/resources/public/ts/directives/file-viewer/file-viewer.html
tooltip now display name + extension
-When overring a file tilte display name + extension
https://jira.support-ent.fr/browse/MAG-280
> fix(fileViwer) #MAG-280: tooltip now display name + extension

- src/main/resources/public/sass/global/components/directives/_card-preview-image.scss
- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
CSS changes for better scrollbar in file viewer for txt
https://jira.support-ent.fr/browse/MAG-282
La scroll bar doit être sur le cadre et non en dessous du texte :
> fix(FileViewer) #MAG-282 : new css to better txt handling

- src/main/resources/public/sass/global/components/directives/_file-viewer.scss
affichage correct des csv dans un petit écran
code by @Rseuret 
ouvrir un csv en lecture, vérifier que les informations s'affichent correctement
[MAG-281](https://jira.support-ent.fr/browse/MAG-281)
> fix(csv): #MAG-281 fix csv display

- src/main/resources/public/sass/global/components/directives/_card-list.scss
- src/main/resources/public/sass/global/components/directives/_section-list.scss
- src/main/resources/public/ts/directives/section-list/section-list.html
No more scrolls when not needed
[MAG-271](https://jira.support-ent.fr/browse/MAG-271)
> fix(scroll): #MAG-271 fix display scroll

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/controller/ShareController.java
- src/main/java/fr/cgi/magneto/service/WorkspaceService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultWorkspaceService.java
Add a new filter to check old rights : If an user try to give less rights to a files inside a shared folder on the same group/user, we throw an error 
https://jira.support-ent.fr/browse/MAG-287
> feat(ShareService) #MAG-287 : Add a new filter to check old rights

- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/es.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/public/sass/global/components/_icons.scss
- src/main/resources/public/sass/global/components/directives/_board-list-folder.scss
- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/directives/board-list/board-list-folder/board-list-folder.html
- src/main/resources/public/ts/directives/board-list/board-list.directive.ts
- src/main/resources/public/ts/directives/index.ts
- src/main/resources/public/ts/directives/message-lightbox/message-lightbox.directive.ts
- src/main/resources/public/ts/directives/message-lightbox/message-lightbox.html
- src/main/resources/public/ts/directives/share-panel-lightbox/share-panel-lightbox.directive.ts
- src/main/resources/public/ts/directives/share-panel-lightbox/share-panel-lightbox.html
- src/main/resources/public/ts/models/folder.model.ts
- icônes de dossiers partagés  
- appels API lors de l'ouverture de la pop-up de partage de dossier
- partage bloqué (front) pour les tableaux dans un dossier ptg  
- message dans la lightbox lors du ptg d'un dossier
- light box lors du drag n drop OUT (dans le dossier) 
- light box lors du drag n drop IN (en dehors du dossier)
- partager un dossier --> vérifier message fenêtre de ptg + icône du dossier une fois ptg
- essayer de partager un tableau dans un dossier ptg
- déplacer un tableau dans et en dehors d'un dossier ptg (apparition des lightbox)
[MAG-285](https://jira.support-ent.fr/browse/MAG-285)
> feat(share): #MAG-285 add front end rules for folder share

- src/main/resources/public/ts/directives/board-list/board-list-folder/board-list-folder.html
- src/main/resources/public/ts/directives/share-panel-lightbox/share-panel-lightbox.directive.ts
- icon is updated after (un)share
- share icon does not appear when share object is empty
(un)share folder and check if icon has changed
[MAG-300](https://jira.support-ent.fr/browse/MAG-300)
> fix(icon): #MAG-300 fix shared folder icon behaviour

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/controller/ShareController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/model/FolderPayload.java
- src/main/java/fr/cgi/magneto/model/share/SharedElem.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/FolderService.java
- src/main/java/fr/cgi/magneto/service/ServiceFactory.java
- src/main/java/fr/cgi/magneto/service/ShareService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultWorkspaceService.java
- src/main/resources/i18n/timeline/de.json
- src/main/resources/i18n/timeline/en.json
- src/main/resources/i18n/timeline/es.json
- src/main/resources/i18n/timeline/fr.json
- src/main/resources/i18n/timeline/it.json
- src/main/resources/i18n/timeline/pt.json
- src/main/resources/view-src/notify/share_folder.html
- src/main/resources/view-src/notify/share_folder.json
- src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
- src/test/java/fr/cgi/magneto/service/CardServiceTest.java
Handle share for folders 
Check if a right is apply to all the folder s children
Check if the old rights are still saved with the new rights applied 
##API descriptions : 
https://confluence.support-ent.fr/display/RN/Share
> feat(Folder) #MAG-286 : handle share folders in back 

- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/helper/ShareHelper.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
Board rights are updated during drag and drop
/!\ PR will be merged after this one https://github.com/OPEN-ENT-NG/magneto/pull/102
drag and drop a board in and out of a shared file and see the right change
[MAG-299](https://jira.support-ent.fr/browse/MAG-299)
> feat(share): #MAG-299 handle rights during drag and drop

- src/main/java/fr/cgi/magneto/controller/ShareController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/service/ServiceFactory.java
- src/main/java/fr/cgi/magneto/service/ShareBookMarkService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultShareBookMarkService.java
fix notifications and bug when sharing boards 
https://jira.support-ent.fr/browse/MAG-188
> fix(Notifications)#MAG-286: fix notifications

- src/main/java/fr/cgi/magneto/controller/ShareController.java
- src/main/java/fr/cgi/magneto/model/share/SharedElem.java
- src/main/java/fr/cgi/magneto/service/ShareService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
better handle of bookmark for folders and boards 
check if share folder workds with all the type ( group/bookmark/user)
> fix(Notifications) #MAG-286: better handle of bookmark

- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/directives/board-list/board-list-item.html
* rename file to keep old data
* fix shared option in toaster
* shared icon no longer displayed when shared array is empty
-Remove all shared right from a board must hide shared icon
-Old shared boards get the corrects rights
-Can share a board inside a folder 
https://jira.support-ent.fr/browse/MAG-301
> fix(Share): #MAG-301 fix share boards

- src/main/resources/public/sass/global/components/directives/_card-list-item.scss
- src/main/resources/public/ts/directives/card-list/card-list-item/card-list-item-preview/card-list-item-preview.html
fix link icon which wasn't at the same size as the other icons
check link icons and compare to all icons
[MAG-266](https://jira.support-ent.fr/browse/MAG-266)
> fix(icons) : #MAG-266 fix link icon which wasn't at the same size as the other icons.

- src/main/resources/public/ts/directives/linker/linker.directive.ts
Magneto links works again : you can search boards
click on 'create link' when inside a board
try to search and select another board
[MAG-278](https://jira.support-ent.fr/browse/MAG-278)
> fix(linker): #MAG-278 fix board links

- src/main/java/fr/cgi/magneto/model/boards/BoardPayload.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
Create a folder or a board inside shared folder now have the parent's shared rights
-Create a folder inside a shared folder make the new folder with the parent's right
-Create a board inside a shared folder make the new folder with the parent's right
https://jira.support-ent.fr/browse/MAG-302
> fix(folderCreate): #MAG-302 create folder and board inside shared folder

- src/main/resources/public/template/boards.html
can share folder in a shared folder
https://jira.support-ent.fr/browse/MAG-301
> fix(shareFolder): #MAG-301 can share folder in a shared folder

- src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
swap to forbidden instead of unauthorized
> fix(shareController): #MAG-287 swap to forbidden instead of unauthorized

- src/main/java/fr/cgi/magneto/controller/BoardController.java
- src/main/java/fr/cgi/magneto/controller/CardController.java
- src/main/java/fr/cgi/magneto/controller/SectionController.java
- src/main/java/fr/cgi/magneto/core/constants/Field.java
- src/main/java/fr/cgi/magneto/core/enums/Events.java
- change eventStore syntax to avoid issues on resource creation
- check if creation of board, magnet or section works properly
- check if these events are stored
https://jira.support-ent.fr/browse/MO-369
> fix(eventstore): #MO-369 change CREATE events with resource types

- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
drag and drop gets folders shared data before updating them
drag and drop board into shared folder and see if the board's rights are updated
[MAG-299](https://jira.support-ent.fr/browse/MAG-299)
> fix(dragAndDrop): #MAG-299 fix drag and drop async implementation

- src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
- src/main/resources/public/ts/directives/board-list/board-list.directive.ts
fix share a folder inside a folder
https://jira.support-ent.fr/browse/MAG-287
> fix(shareFolder): #MAG-287 fix share a folder inside a folder

- src/main/resources/public/sass/global/components/directives/_board-nav.scss
> fix(dividerCss): #MAG-268 fix divider add more pxl

- src/main/resources/public/sass/global/components/directives/_section-list.scss
> fix(sectionHorizontal): #MAG-304 fix sections horizontal css

- src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
keep superior right when sharing parent folder
share child folder with superior rights
share parent folder with lower rights
[MAG-286](https://jira.support-ent.fr/browse/MAG-286)
> fix(shareFolder): #MAG-286 keep superior right when sharing parent folder

- src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
handle remove rights in checkrights
https://jira.support-ent.fr/browse/MAG-314
> fix(shareRights): #MAG-314 handle remove rights

- src/main/java/fr/cgi/magneto/service/ShareService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
Fix bug when restrict rights it deletes the rights 
> fix(sharedFolder): #MAG-286 fix rights when restricts

- src/main/java/fr/cgi/magneto/controller/BoardController.java
- src/main/java/fr/cgi/magneto/controller/FakeRight.java
- src/main/java/fr/cgi/magneto/controller/FolderController.java
- src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
- src/main/java/fr/cgi/magneto/core/constants/Mongo.java
- src/main/java/fr/cgi/magneto/core/constants/Rights.java
- src/main/java/fr/cgi/magneto/helper/ShareHelper.java
- src/main/java/fr/cgi/magneto/security/CreateBoardRight.java
- src/main/java/fr/cgi/magneto/security/CreateFolderRight.java
- src/main/java/fr/cgi/magneto/security/DeleteFolderRight.java
- src/main/java/fr/cgi/magneto/security/DuplicateBoardRight.java
- src/main/java/fr/cgi/magneto/security/ManageBoardRight.java
- src/main/java/fr/cgi/magneto/security/ManageFolderRight.java
- src/main/java/fr/cgi/magneto/security/MoveBoardRight.java
- src/main/java/fr/cgi/magneto/security/SetShareRights.java
- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/directives/board-container-header/board-container-header.directive.ts
- src/main/resources/public/ts/directives/board-container-header/board-container-header.html
- src/main/resources/public/ts/utils/share.utils.ts
APIs and front-end are secured depending on rights
check documentation 
[MAG-287](https://jira.support-ent.fr/browse/MAG-287)
> feat(rights): #MAG-287 implement rights security

- src/main/java/fr/cgi/magneto/core/constants/Mongo.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/FolderService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
better handling of deleted shared folders
https://jira.support-ent.fr/browse/MAG-313
https://jira.support-ent.fr/browse/MAG-313
>  fix(shareRights): #MAG-313 delete shared folders

- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
now drag and drop share workspace rights too
https://jira.support-ent.fr/browse/MAG-315
> fix(Workspace): #MAG-315 now drag and drop share workspace rights too

- src/main/java/fr/cgi/magneto/core/constants/Rights.java
- src/main/java/fr/cgi/magneto/security/CreateBoardRight.java
- src/main/java/fr/cgi/magneto/security/CreateFolderRight.java
- src/main/java/fr/cgi/magneto/security/MoveBoardRight.java
- src/main/resources/i18n/de.json
- src/main/resources/i18n/en.json
- src/main/resources/i18n/es.json
- src/main/resources/i18n/fr.json
- src/main/resources/i18n/it.json
- src/main/resources/i18n/pt.json
- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/directives/board-move-lightbox/board-move-lightbox.directive.ts
- src/main/resources/public/ts/directives/message-lightbox/message-lightbox.directive.ts
- src/main/resources/public/ts/directives/message-lightbox/message-lightbox.html
- src/main/resources/public/ts/magnetoBehaviours.ts
front security for drag and drop and move board
/!\ two commits will be merged to keep workflow right fix separate
tests (initial folder/target folder) :
//no right lightbox
- not board owner
//Enter shared folder lightbox
- owner/has right
- my boards/has right
- has right/has right
//exit shared folder lightbox
- has right/owner
// no lightbox
- owner/owner
//no right lightbox
- no right/no right
- not right/OK
- OK/no right
[MAG-316](https://jira.support-ent.fr/browse/MAG-316)
> feat(rights): #MAG-316 add right security for drag and drop

- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
fix a bug where you cant remove lower rights on a folder
https://jira.support-ent.fr/browse/MAG-340
> fix(Share): #MAG-340 fix a bug where you cant lower rights

- src/main/java/fr/cgi/magneto/controller/FolderController.java
fix a bug where you cant restore a folder
https://jira.support-ent.fr/browse/MAG-301
> fix(FolderContoller): #MAG-301 fix a bug where you cant restore a folder

- JenkinsFile
- docker-compose.yml
- Upgrade the docker-compose file so it can be used with newer versions of `docker compose`.
- Update Jenkinsfile to display the name of the branch and the version of the module on Jenkins board
Executed `build.sh install` to check that it still works.
> ci: upgrade docker-compose

- src/main/java/fr/cgi/magneto/controller/FolderController.java
fix a bug where you cant delete a folder
> fix(FolderContoller): #MAG-301 fix a bug where you cant delete a folder

- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/directives/board-container-header/board-container-header.directive.ts
- src/main/resources/public/ts/directives/board-container-header/board-container-header.html
- src/main/resources/public/ts/directives/board-move-lightbox/board-move-lightbox.directive.ts
- src/main/resources/public/ts/utils/share.utils.ts
- d & d : owner-owner + ptg : lightbox 
- déplacer out : erreur qd pas de droits (fenetre) 
- btn "creer tableau" encore la + idem "creer dossier"
- d & d : owner-owner + ptg : lightbox 
- déplacer out : erreur qd pas de droits (fenetre) 
- btn "creer tableau" encore la + idem "creer dossier"
[MAG-316](https://jira.support-ent.fr/browse/MAG-316)
> fix(rights): #MAG-316 fix front rights

- src/main/java/fr/cgi/magneto/controller/BoardAccessController.java
- src/main/java/fr/cgi/magneto/model/boards/Board.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
add cards number to api mobile 
API:
https://confluence.support-ent.fr/display/RN/Board+Access
https://jira.support-ent.fr/browse/MAG-341
> fix(appMobile): #MAG-341 cards number

- src/main/java/fr/cgi/magneto/security/DuplicateCardRight.java
- src/main/java/fr/cgi/magneto/security/ManageBoardRight.java
- src/main/java/fr/cgi/magneto/security/ManageFolderRight.java
- src/main/java/fr/cgi/magneto/security/ReadBoardRight.java
- src/main/java/fr/cgi/magneto/security/WriteBoardRight.java
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/models/folder-tree.model.ts
try to call actions via postman
check create folder and board buttons depending on folder rights
[MAG-347](https://jira.support-ent.fr/browse/MAG-347)
> fix(rights): #MAG-347 fix action rights

- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/core/enums/folder-type.enum.ts
- src/main/resources/public/ts/core/enums/rights.enum.ts
- src/main/resources/public/ts/directives/board-move-lightbox/board-move-lightbox.directive.ts
- src/main/resources/public/ts/models/folder.model.ts
- src/main/resources/public/ts/utils/share.utils.ts
see documentation https://confluence.support-ent.fr/display/RN/Partage+de+dossiers+-+conception+fonctionnelle
[MAG-316](https://jira.support-ent.fr/browse/MAG-316)
> fix(move): #MAG-316 fix board move

- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
fix a bug when boards appears in home and folder
- Drag and drop a board inside a folder : the folder must appear only inside the folder
- Share a board inside a folder to a user without shared rights on the folder : the board must appear at the main page
> fix(Boards) : #MAG-286 fix a bug when boards appears in home and folder

- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
fix a bug when boards are filtered too soon
Folder with less than 30 boards must show all their boards 
> fix(Boards) : #MAG-286 fix a bug when boards are filtered too soon

- src/main/java/fr/cgi/magneto/controller/MagnetoController.java
add config route
connect with superadmin and test config route
[MAG-362](https://jira.support-ent.fr/browse/MAG-362)
> feat(config): #MAG-362 add config route

- src/main/resources/public/ts/utils/share.utils.ts
fix group right verification
[MAG-347](https://jira.support-ent.fr/browse/MAG-347)
> fix(rights): #MAG-347 fix group right verification

- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
check if user is owner of boards to move boards ( front )
https://jira.support-ent.fr/browse/MAG-315
> fix(Boards): #MAG-315 now check boards owner to move boards

- src/main/resources/public/sass/global/components/directives/_card-list.scss
- src/main/resources/public/ts/directives/section-list/section-list.html
next section has minimum height
check section height
https://jira.support-ent.fr/browse/MAG-304
> fix(section): #MAG-304 fix horizontal section

- src/main/resources/public/ts/controllers/boards.controller.ts
Share a board with contrib right , user can now duplicate this board 
https://jira.support-ent.fr/browse/MAG-374
> fix(Duplicate) #MAG-374 : fix duplicate rights

- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
fix move board:
- async problem
- object problem
check documentation
[MAG-316](https://jira.support-ent.fr/browse/MAG-316)
> fix(move): #MAG-316 fix move board process

- src/main/java/fr/cgi/magneto/controller/BoardController.java
- src/main/java/fr/cgi/magneto/service/BoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
handle restore elem into shared folders 
-Create folder with folders and boards inside . Share the folder . If any elem is deleted and restored , they mus appear inside the folder and have the same shared rights 
https://jira.support-ent.fr/browse/MAG-315
> fix(SharedFolders): #MAG-313 handle restore

- src/main/java/fr/cgi/magneto/security/MoveBoardRight.java
- src/main/resources/public/ts/controllers/boards.controller.ts
Fix déplacement en d&d de  2 tableaux, 1 à moi, 1 pas à moi 
[MAG-381](https://jira.support-ent.fr/browse/MAG-381)
> fix(move): #MAG-381 fix multiple board drag & drop rights

- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
handle folders without boards of folders owner
https://jira.support-ent.fr/browse/MAG-313
> fix(Delete): #MAG-313 handle folders without boards of folders owner

- src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
fix a bug check folderId instead of boardId
https://jira.support-ent.fr/browse/MAG-313
> fix(Delete): #MAG-313 fix a bug check folderId instead of boardId

- src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
now doesnt apply share  on deleted elements
https://jira.support-ent.fr/browse/MAG-313
> fix(Delete): #MAG-313 fix share : now doesnt apply on deleted elements

- src/main/java/fr/cgi/magneto/security/MoveBoardRight.java
- src/main/resources/public/template/boards.html
- src/main/resources/public/ts/controllers/boards.controller.ts
- src/main/resources/public/ts/directives/board-move-lightbox/board-move-lightbox.directive.ts
allow board move is not owner under conditions
when we are not a board owner, we can move them under 
[MAG-382](https://jira.support-ent.fr/browse/MAG-382)
> fix(move): #MAG-382 allow board move is not owner under conditions

- src/main/resources/public/ts/directives/card-list/card-preview-image.directive.ts
fix controller not init
https://jira.support-ent.fr/browse/MAG-376
> fix(DisplayCard): #MAG-376 fix controller not init

- src/main/resources/public/sass/global/components/containers/_board.scss
- src/main/resources/public/template/board.html
- src/main/resources/public/ts/controllers/board-view.controller.ts
fix board size when cards are present in free layout
create free layout board with one card, check board height
[MAG-304](https://jira.support-ent.fr/browse/MAG-304)
> fix(freeLayout): #MAG-304 fix free layout card-list size

- src/main/java/fr/cgi/magneto/core/constants/Mongo.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
fix get boards Again now handle board with one folder
https://jira.support-ent.fr/browse/MAG-383
> fix(Boards): #MAG-383 fix get boards now handle board with one folder

- frontend/src/routes/app/index.tsx
- frontend/src/routes/board/index.tsx
- frontend/src/routes/index.tsx
- frontend/src/routes/info/index.tsx
- frontend/src/routes/read/index.tsx
- frontend/src/routes/user/index.tsx
feat(routes) : #MAG-388 add all main routes of magneto.
Check all different routes and check if the backend (with the API) is working.
The new routes are http://localhost:4200/board/{id}/view and http://localhost:4200/board/{id}/reading
[MAG-388](https://jira.support-ent.fr/browse/MAG-388)
> feat(routes) : #MAG-388 add all main routes of magneto

- backend/src/main/java/fr/cgi/magneto/controller/MagnetoController.java
- build.sh
- frontend/build.sh
- frontend/src/routes/index.tsx
- frontend/vite.config.ts
change router type to work in production mode
Check all different routes and check if the backend (with the API) is working.
The new routes are [http://localhost:4200/board/{id}/view](http://localhost:4200/board/%7Bid%7D/view) and [http://localhost:4200/board/{id}/reading](http://localhost:4200/board/%7Bid%7D/reading)
[MAG-389](https://jira.support-ent.fr/browse/MAG-389)
> feat(react): #MAG-388 change router type to work in production mode

- frontend/src/components/create-folder/CreateFolder.scss
- frontend/src/components/create-folder/CreateFolder.tsx
- frontend/src/models/board.model.ts
- frontend/src/routes/app/index.tsx
- frontend/src/services/api/folders.service.ts
Adds a modal to create folders (and a temporary button).
Check if the folder is created, if the modal has the title right depending on its closed or opened state.
[MAG-351](https://jira.support-ent.fr/browse/MAG-351)
> feat(folders) : #MAG-351 add modal to create folders (and a temporary button).

- frontend/package.json
- frontend/src/components/create-tab/createTab.tsx
- frontend/src/components/file-viewer/FileViewerModel.ts
- frontend/src/components/magnets-collection/MagnetsCollectionModal.scss
- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
- frontend/src/components/side-bar/SideBarButtons.tsx
- frontend/src/models/board.model.ts
- frontend/src/models/card-comment.model.ts
- frontend/src/models/card.model.ts
- frontend/src/models/cards-filter.model.ts
- frontend/src/services/api/boards.service.ts
- frontend/src/services/api/cards.service.ts
feat(favorites) : #MAG-352 adds modal of favorite cards display with a searchbar and the option to display them with or without boards.
Check if its functionnally the same as the one on angularJS (display of cards, filter by searchbar, change display to add boards name).
> feat(favorites) : #MAG-352 adds modal of favorite cards display.

- frontend/src/components/create-board/CreateBoard.tsx
- frontend/src/hooks/useImageHandler.ts
Fix thumbnail and background pictures not being taken in account (now registers in workspace and get the url into the DB, juste like in Angular but without the <image-select> component which is not finished yet.
Test board creation with/without thumbnail and/or background (you're not supposed to register without a thumbnail, but you can without a background)
[MAG-353](https://jira.support-ent.fr/browse/MAG-353)
> fix(boards) : #MAG-353 fix thumbnail and background pictures not being taken in account

- frontend/src/components/board-list/BoardList.tsx
- frontend/src/components/folder-list/FolderList.tsx
- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
- frontend/src/routes/app/index.tsx
- frontend/src/services/api/boards.service.ts
fix searchbar not working for boards and folders
Check if searchbar gives all infos about folders and boards (all boards, not only the one on actual folder). Also check is searchbar is resetting when switching current folder.
[MAG-391](https://jira.support-ent.fr/browse/MAG-391)
> fix(boards) : #MAG-391 fix searchbar not working for boards and folders

- frontend/index.html
- frontend/src/components/create-board/CreateBoard.scss
- frontend/src/components/create-board/CreateBoard.tsx
- frontend/src/components/create-folder/CreateFolder.tsx
- frontend/src/components/drawer-sidebar/DrawerSideBar.tsx
- frontend/src/components/header/Header.scss
- frontend/src/components/header/Header.tsx
- frontend/src/components/side-bar/SideBar.tsx
- frontend/src/components/side-bar/SideBarButtons.tsx
- frontend/src/hooks/useAdaptColumns.ts
- frontend/src/hooks/useWindowDimensions.ts
- frontend/src/main.tsx
- frontend/src/routes/app/index.scss
- frontend/src/routes/app/index.tsx
fix main page and board creation responsivity and added a sidebar drawer for lower sizes (<1024px of width)
fix wrong tab name (myApp instead of Magnéto)
Test magneto on different size of screen (for the main page and the board creation)
[MAG-427](https://jira.support-ent.fr/browse/MAG-427)
> fix(index) : #MAG-427 fix main page and board creation responsivity, and wrong tab name.

- frontend/src/components/magnets-collection/MagnetsCollectionModal.scss
- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
Fix magnet favorites visuals not close enough to 1.x Magneto visuals, also fix button shenaningans when leaving and re-entering the modal.
Check visually and functionnally if its close enough to the prod version.
[MAG-352](https://jira.support-ent.fr/browse/MAG-392)
> fix(favorites) : #MAG-352 fix magnet favorites visuals

- backend/gradle.properties
- backend/src/main/java/fr/cgi/magneto/config/MagnetoConfig.java
- backend/src/main/java/fr/cgi/magneto/controller/MagnetoController.java
- backend/src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
- backend/src/main/java/fr/cgi/magneto/service/ServiceFactory.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- frontend/package.json
- frontend/src/components/share-modal/ShareModalMagneto.tsx
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/core/enums/resource-big-type.enum.ts
- frontend/src/main.tsx
- frontend/src/models/board.model.ts
- frontend/src/models/folder.model.ts
- frontend/src/stores/index.ts
- frontend/src/stores/rights/store.ts
- frontend/src/utils/checkUserRight.ts
- frontend/vite.config.ts
Adds a share modal to let other ppl access to folders or boards (i18n are not implemented yet, it will be very very soon in a dedicated chore in dev-react)
Check if the modal is functionning properly with both folders and boards (try different roles)
> feat(share) : #MAG-350 add share modal to let other ppl access to folders or boards.

- frontend/src/components/board-item/BoardItem.scss
- frontend/src/components/board-item/BoardItem.tsx
- frontend/src/components/board-list/BoardList.scss
- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/folder-title/FolderTitle.tsx
- frontend/src/components/folder-title/style.ts
- frontend/src/components/folder-title/types.ts
- frontend/src/components/magnets-collection/MagnetsCollectionModal.scss
- frontend/src/dictionaries/en.json
- frontend/src/dictionaries/fr.json
- frontend/src/routes/app/index.tsx
+ **placeHolder SearchBar changed + style like Blog.**
+ **BoardCard reworked : img, ellipsis on title, bottom reworked.**
+ **Icons in FolderCards**
+ **Cpt FolderTitle**
> fix(re7) : #MAG-391-redo fix all +FolderTitle cpt

- frontend/src/components/board-item/BoardItem.scss
- frontend/src/components/board-item/BoardItem.tsx
- frontend/src/components/drawer-sidebar/DrawerSideBar.tsx
- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/folder-list/FolderList.tsx
- frontend/src/components/folder-title/style.ts
- frontend/src/components/side-bar/SideBar.tsx
- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/components/tree-view/utils.ts
- frontend/src/models/folder.model.ts
- frontend/src/providers/FoldersNavigationProvider/index.tsx
- frontend/src/providers/FoldersNavigationProvider/types.ts
- frontend/src/providers/FoldersNavigationProvider/useInitialCurrentFolder.ts
- frontend/src/providers/FoldersNavigationProvider/utils.ts
- frontend/src/routes/app/index.scss
- frontend/src/routes/app/index.tsx
+ **SearchBar style + searching fixed**
+ **FolderTitle on load, img in cards, date format, cards icons, cards icon style, folder icon color fixed+ "0" in dom fixed**
> fix(re7) : #MAG-391-redo2 fix several problems including treenav problems

- frontend/src/components/create-folder/CreateFolder.tsx
fix modal CSS not being ISO enough of blog, mindmap, ...
Check if the visuals are the same as blog ones.
[MAG-351](https://jira.support-ent.fr/browse/MAG-351)
> fix(folder) : #MAG-351 fix modal to be iso with explorer

- frontend/src/main.tsx
+ fix appName
modal responsive already fixed
> fix(appname) : #MAG-427 fix appname

- frontend/src/components/create-folder/CreateFolder.scss
- frontend/src/components/tree-view/TreeViewContent.scss
> fix(treeview) : #MAG-390 no more foldUnfold tooltip

- frontend/src/components/magnets-collection/MagnetsCollectionModal.scss
- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
fix icon placement/spacing
Check in favorites if the icon has a better placement (see issue comment)
> fix(favorites) : #MAG-352 fix icon placement/spacing

- frontend/src/components/create-folder/CreateFolder.tsx
fix folders created not being put in the right place (now use correctly the currentFolder)
Try to create folders in different places (the 3 special folders, and inside some folders/subfolders)
[MAG-351](https://jira.support-ent.fr/browse/MAG-351)
> fix(folders) : #MAG-351 fix subfolder creation

- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/folder-list/FolderList.tsx
> fix(FolderList) : #MAG-391 fix selected folders

- backend/src/main/java/fr/cgi/magneto/config/MagnetoConfig.java
- frontend/src/components/board-keywords-input/BoardKeywordsInput.tsx
- frontend/src/components/board-public-share-modal/BoardPublicShareModal.scss
- frontend/src/components/board-public-share-modal/BoardPublicShareModal.tsx
- frontend/src/components/delete-modal/DeleteModal.tsx
- frontend/src/components/move-board/MoveBoard.tsx
- frontend/src/components/share-modal/ShareModalMagneto.tsx
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/models/board.model.ts
Fix various problems : missing popup sentence on predeleting, some buttons order, move modal not working, public share modal missing and tab name changing to "magneto/boards"
Test all toaster functionnalities in all places (MyBoards, Trash, Public, in subfolders) on both folders and boards
[#MAG-355](https://jira.support-ent.fr/browse/MAG-355)
> fix(toaster) : #MAG-355 fix various problems linked to the toaster

- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
fix folders sharing not working when registering changes in the modal
Try to share folders and check their status
> fix(share) : #MAG-350 fix folders sharing not working

- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/side-bar/SideBar.tsx
- frontend/src/providers/FoldersNavigationProvider/index.tsx
- frontend/src/providers/FoldersNavigationProvider/types.ts
fix select new folder after creation
> fix(foldersrefetch): #MAG-391 sync rtk refetch with provider

- frontend/src/components/create-folder/CreateFolder.tsx
add ":" after label
check label
[MAG-351](https://jira.support-ent.fr/browse/MAG-351)
> fix(create-folder): #MAG-351 fix create folder label

- frontend/src/routes/app/index.tsx
fix case with folders and no boards / boards and no folders
check case with folders and no boards / boards and no folders
[MAG-424](https://jira.support-ent.fr/browse/MAG-424)
> fix(empty-state): #MAG-424 fix empty state

- frontend/src/components/board-public-share-modal/BoardPublicShareModal.tsx
- frontend/src/components/create-folder/CreateFolder.tsx
- frontend/src/components/delete-modal/DeleteModal.tsx
- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/folder-list/FolderList.tsx
- frontend/src/components/move-board/MoveBoard.tsx
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/providers/FoldersNavigationProvider/utils.ts
- frontend/src/services/api/folders.service.ts
Several issues fixed, 2 left.
check [MAG 355](https://jira.support-ent.fr/browse/MAG-355)
> fix(toaster): #MAG-355 fix several issues

- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
> fix(magnetcolletion): #MAG-352 add emptyState

- frontend/src/components/board-item/BoardItem.tsx
> fix(board_item) : #MAG-427 fix owner tooltip

- frontend/src/components/toaster-container/ToasterContainer.tsx
> fix(toaster): #MAG-350 fix toaster rights check

- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
> fix(magnet-collection) : #MAG-352 indentation issue fixed

- frontend/src/components/message-modal/MessageModal.tsx
- frontend/src/i18n.ts
> fix(message-modal) : #MAG-355 i18n param fixed

- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
> fix(magnet-collection) : #MAG-352 trying to fix lowercase error in ng2

- frontend/src/components/create-folder/CreateFolder.tsx
- frontend/src/components/drawer-sidebar/DrawerSideBar.tsx
- frontend/src/components/drawer-sidebar/style.scss
- frontend/src/components/move-board/MoveBoard.tsx
- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/components/tree-view/TreeViewContent.scss
- frontend/src/components/tree-view/utils.ts
- frontend/src/models/folder-tree.model.ts
- frontend/src/providers/FoldersNavigationProvider/useInitialPublicFolderObject.ts
> fix(treeview): #MAG-390 several issues fixed

- backend/src/main/resources/i18n/de.json
- backend/src/main/resources/i18n/en.json
- backend/src/main/resources/i18n/es.json
- backend/src/main/resources/i18n/fr.json
- backend/src/main/resources/i18n/it.json
- backend/src/main/resources/i18n/pt.json
- frontend/src/components/delete-modal/DeleteModal.tsx
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/models/folder-tree.model.ts
- frontend/src/providers/BoardsNavigationProvider/index.tsx
- frontend/src/providers/BoardsNavigationProvider/utils.ts
- frontend/src/providers/FoldersNavigationProvider/index.tsx
- frontend/src/providers/FoldersNavigationProvider/utils.ts
> fix(toaster+treeview) : #MAG-355 fix delete folders display and toaster interactions

- backend/src/main/resources/i18n/de.json
- backend/src/main/resources/i18n/en.json
- backend/src/main/resources/i18n/es.json
- backend/src/main/resources/i18n/fr.json
- backend/src/main/resources/i18n/it.json
- backend/src/main/resources/i18n/pt.json
- frontend/src/components/board-item/BoardItem.scss
- frontend/src/components/board-item/BoardItem.tsx
- frontend/src/components/board-list/BoardList.tsx
- frontend/src/components/board-list/utils.ts
- frontend/src/components/folder-item/FolderItem.scss
- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/folder-title/style.ts
- frontend/src/components/side-bar/SideBar.tsx
- frontend/src/routes/app/index.scss
- frontend/src/routes/app/index.tsx
> #MAG-391 fix several style issues

- frontend/src/components/create-board/CreateBoard.scss
- frontend/src/components/create-board/CreateBoard.tsx
> fix(createBoard): #MAG-353 fix textarea

- backend/src/main/resources/i18n/de.json
- backend/src/main/resources/i18n/en.json
- backend/src/main/resources/i18n/es.json
- backend/src/main/resources/i18n/fr.json
- backend/src/main/resources/i18n/it.json
- backend/src/main/resources/i18n/pt.json
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/routes/app/index.tsx
**when no search result**
**when empty folder**
> fix(emptyState) : #MAG-391 fix emptyState  emptyFolder

- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/providers/FoldersNavigationProvider/index.tsx
- frontend/src/providers/FoldersNavigationProvider/types.ts
- frontend/src/providers/FoldersNavigationProvider/utils.ts
> fix(arbo) #MAG-424 fix arbo

- frontend/src/components/magnets-collection/FavoriteViewByBoard.tsx
- frontend/src/components/magnets-collection/FavoriteViewByCard.tsx
- frontend/src/components/magnets-collection/MagnetsCollectionModal.scss
- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
fix view by board displaying boards without favorite magnets (+ refacto'd to have 2 more separate components)
Check if modal favorites are working, particulary the board view (favorites should be displayed by boards)
> fix(favorites) : #MAG-350 fix view by board displaying boards without favorite magnets (+ refacto'd)

- frontend/src/components/board-list/utils.ts
[MAG-427](https://jira.support-ent.fr/browse/MAG-427)
> fix(search): #MAG-327 handle undefined value

- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
fix sharing modal not working on folders not already shared
> fix(share) : #MAG-350 fix sharing modal not working on folders not already shared

- frontend/src/components/board-item/BoardItem.tsx
fix searchbar resetting when deleting a letter in it because of dnd interactions
Check dnds interactions and if the searchbar is working
[MAG-392](https://jira.support-ent.fr/browse/MAG-392)
> fix(search) : #MAG-392 fix searchbar resetting when deleting a letter in it because of dnd interactions

- pom.xml
- src/main/java/fr/cgi/magneto/Magneto.java
- src/main/java/fr/cgi/magneto/helper/FutureHelper.java
- src/main/java/fr/cgi/magneto/security/ReadBoardRight.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultCommentService.java
- src/main/java/fr/cgi/magneto/service/impl/DefaultSectionService.java
- src/main/java/fr/cgi/magneto/service/impl/MagnetoRepositoryEvents.java
Migration from Vertx3 to Vertx4
https://jira.support-ent.fr/browse/MAG-421
> feat(migration): #MAG-421 Vertx Migration

- frontend/src/components/board-item/BoardItem.tsx
- frontend/src/components/board-list/BoardList.tsx
- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/providers/BoardsNavigationProvider/index.tsx
- frontend/src/routes/app/index.tsx
cannot rename folder if it is in the bin folder --> /!\ the only changes related to this dev are in ToasterContainer.tsx, the rest is linter fixes
cannot rename folders when in deleted folder
[MAG-355](https://jira.support-ent.fr/browse/MAG-355)
> fix(rights): #MAG-355 fix toaster rignts for folders

- frontend/src/components/folder-item/FolderItem.scss
- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/message-modal/MessageModal.tsx
- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/components/tree-view/TreeViewContent.scss
Fix boards move interactions with folders in dnd (couldnt move in parent folder, couldnt move from my boards to subfolder, could move in read only folder when shouldnt be able to)
Fix modal interactions (confirm button there when shouldnt, closing cross missing)
Check all those interactions described up there and more generally check if the dnd is functionning as needed.
[MAG-392](https://jira.support-ent.fr/browse/MAG-392)
> fix(dnd) : #MAG-392 fix dnd rights and popup buttons

- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
fix favorite by board view not working because it didnt load boards outside of main page.
Check if the favorite by board view is working correctly with all boards possessed.
> fix(favorites) : #MAG-352 fix favorite by board view

- frontend/src/components/board-item/BoardItem.scss
- frontend/src/components/folder-list/FolderList.scss
- frontend/src/components/folder-list/FolderList.tsx
- frontend/src/components/folder-title/style.ts
Fix board tooltip stuttering when the mouse was too low, and fix display issues with bottom boards being sometimes overflowing on the screen, resulting in missing pieces of information
Check if the boards are displaying correctly now, and if the tooltip isnt stuttering anymore
[MAG-391](https://jira.support-ent.fr/browse/MAG-391)
> fix(boards) : #MAG-391 fix board tooltip and display

- frontend/src/components/board-item/BoardItem.tsx
fix searchbar regression on deleting a letter which could display at least one more board (it would delete the whole search text)
Check if the searchbar is working correctly
[MAG-427](https://jira.support-ent.fr/browse/MAG-427)
> fix(searchbar) : #MAG-427 fix searchbar regression on deleting letter

- frontend/src/components/empty-state/EmptyState.scss
fix empty state not displayed properly because of float left changes to others elements containing or next to the empty state
Check if the empty state is displayed properly and responsive
[MAG-391](https://jira.support-ent.fr/browse/MAG-391)
> fix(boards) : #MAG-391 fix empty state not displayed properly

- frontend/src/common/ShareModal/hooks/useShare.ts
fix folders and boards not updating when sharing
Try to share/unshare and check if the boards and folders are updating.
> fix(share) : #MAG-350 fix folders and boards not updating when sharing

- frontend/src/components/folder-item/FolderItem.tsx
- frontend/src/components/move-board/MoveBoard.tsx
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/components/tree-view/TreeViewContainer.tsx
- frontend/src/routes/app/index.tsx
owner rights for drag and drop
add rights check for move modal
check all move boards rights
[MAG-392](https://jira.support-ent.fr/browse/MAG-392)
> fix(rights): #MAG-392 fix dragAndDrop and moveModal rights

- frontend/src/common/ShareModal/hooks/useShare.ts
fix regression for sharing folders
Check all rights
> fix(share) : #MAG-350 fix regression for sharing folders

- frontend/src/routes/app/index.tsx
fix drawer treeview not updating correctly (the actual folder was updating but it wasnt highlighted on the first click, only on the second)
Check if the classic sidebar and the drawer sidebar are working correctly
[MAG-390](https://jira.support-ent.fr/browse/MAG-390)
> fix(drawer) : #MAG-390 fix drawer treeview not updating correctly

- frontend/src/components/board-item/BoardItem.tsx
- frontend/src/routes/app/index.scss
- frontend/src/routes/app/index.tsx
Fix bar left side of the board list not going down far enough and fix board item having the wrong magnet count
Check if the main page has no display problems and if the bar left side of the board is displaying correctly and if the magnets counts are now right.
[MAG-391](https://jira.support-ent.fr/browse/MAG-391)
> fix(boards) : #MAG-391 fix bar left side of the board and magnet count

- frontend/src/components/delete-modal/DeleteModal.tsx
- frontend/src/components/magnets-collection/FavoriteViewByBoard.tsx
- frontend/src/components/toaster-container/ToasterContainer.tsx
- frontend/src/hooks/usePredefinedToasts.ts
- frontend/src/hooks/useRestoreBoardsAndFolders.ts
> fix(favoriteModal): #MAG-352 display toaster when duplicating board from favorite modal

- frontend/src/components/magnets-collection/FavoriteViewByBoard.tsx
fix empty state missing on favorite view by board
Vérifier si l'affichage des favoris et la barre de recherche fonctionnent tous bien
> fix(favorite) : #MAG-352 fix empty state missing on favorite view by board

- frontend/src/components/tree-view/TreeViewContainer.tsx
no rights d&d to treeview has no submit button
[MAG-392](https://jira.support-ent.fr/browse/MAG-392)
> fix(modal): #MAG-392 fix no rights modal button

- frontend/src/common/ShareModal/hooks/useShare.ts
- frontend/src/components/toaster-container/ToasterContainer.tsx
Fix sharing modal cache giving us the wrong informations at the 2nd and next openings because of consequential changes throught DnD and folder sharing (now clearing the cache each time we open it).
Check toute la modale de partage et le partage en lui-même (rien n'est censé casser, mais des cas apparaissant comme fonctionnels avant pourraient être mis en lumière comme non fonctionnels maintenant qu'on affiche bien le bon résultat des droits dans la modale à chaque fois).
> fix(share) : #MAG-350 fix sharing modal cache

- frontend/src/common/ShareModal/ShareModal.scss
- frontend/src/common/ShareModal/ShareModal.tsx
Fix warning text missing at the bottom of the sharing modal
Tester pour chaque cas différent que le texte affiché est le bon (cf [ici](https://confluence.support-ent.fr/display/RN/Partage+de+dossiers+-+conception+fonctionnelle#Partagededossiersconceptionfonctionnelle-Messagesdanslafen%C3%AAtredepartage))
> fix(share) : #MAG-350 fix warning text missing

- frontend/src/components/board-item/BoardItem.tsx
> fix(header) : #MAG-438 fix board not clickable

- frontend/src/components/header-view/HeaderView.scss
- frontend/src/components/header-view/HeaderView.tsx
- frontend/src/components/header-view/style.ts
> fix(headerview): #MAG-438 fix header style+hourToast+button

- frontend/src/components/board-view/BoardView.scss
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/header-view/HeaderView.scss
- frontend/src/components/header-view/HeaderView.tsx
- frontend/src/components/header-view/style.ts
- frontend/src/components/zoom-component/ZoomComponent.tsx
- board background if image url exists
- grey background otherwise
- empty state message if there are no cards
- Edifice header is fixed when scrolling
check above cases
[MAG-451](https://jira.support-ent.fr/browse/MAG-451)
> feat(boardView): #MAG-451 implement board view

- frontend/src/components/drop-down-list/DropDownList.tsx
- frontend/src/components/drop-down-list/style.ts
- frontend/src/components/drop-down-list/types.ts
- frontend/src/components/section-name/SectionName.tsx
- frontend/src/components/section-name/style.ts
- frontend/src/components/section-name/types.ts
- frontend/src/components/section-name/useDropDown.ts
- frontend/src/components/section-name/utils.tsx
- frontend/src/models/board.model.ts
- frontend/src/providers/BoardProvider/types.ts
This PR introduces a new dropdown system to the SectionName component, improving its functionality and user interaction. The changes are focused on integrating a more robust dropdown mechanism while maintaining the existing features of SectionName.
- **SectionName Component**: 
- Integrated new dropdown functionality
- Maintained all existing features and behaviors
- Updated to use the new useDropdown hook for state management
- **New Sub-components**:
- **DropDownList**: A reusable component for rendering dropdown items
- **useDropdown**: A custom hook for managing dropdown state across the application
1. **SectionName.tsx**:
- Added integration with useDropdown hook
- Updated dropdown toggle functionality
- Kept all existing input handling and rendering logic intact
2. …
> feat(SectionName): #MAG-449 SectionName + subcpt

- frontend/src/components/board-view/BoardView.scss
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/board-view/style.ts
- frontend/src/components/cards-free-layout/CardsFreeLayout.tsx
- frontend/src/components/cards-free-layout/style.ts
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/routes/board/index.tsx
- frontend/src/services/api/cards.service.ts
[MAG-446](https://jira.support-ent.fr/browse/MAG-446)
> feat(freeLayout): #MAG-446 implement free layout + rearrange view

- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/utils.ts
> Getzoompreference

- frontend/src/components/header-view/HeaderView.tsx
- frontend/src/components/header-view/style.ts
button is only displayed if there is at least 1 card
[MAG-438](https://jira.support-ent.fr/browse/MAG-438)
> fix(boardHeader): #MAG-438 fix button display and save date size

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/types.ts
- frontend/src/components/cards-free-layout/CardsFreeLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/magnets-collection/FavoriteViewByBoard.tsx
- frontend/src/components/magnets-collection/FavoriteViewByCard.tsx
add cards design to the favorite view
Vérifier que dans les 2 vues des favoris au niveau de la page d'accueil, on ait les nouvelles cartes
[MAG-416](https://jira.support-ent.fr/browse/MAG-416)
> feat(favorite) : #MAG-416 add cards design to the favorite view

- frontend/src/components/board-card/style.ts
- frontend/src/components/board-view/style.ts
- frontend/src/components/cards-free-layout/CardsFreeLayout.tsx
- frontend/src/components/cards-free-layout/style.ts
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-horizontal-layout/style.ts
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/cards-vertical-layout/style.ts
card margins in all 3 views, depending on zoom
check zoom for all views
[MAG-446](https://jira.support-ent.fr/browse/MAG-446)
[MAG-447](https://jira.support-ent.fr/browse/MAG-447)
[MAG-448](https://jira.support-ent.fr/browse/MAG-448)
> feat(layouts): #MAG-446 #MAG-447 #MAG-447 handle zoom margins

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/board-description/BoardDescription.tsx
- frontend/src/components/board-view/BoardView.scss
- frontend/src/components/cards-horizontal-layout/style.ts
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/cards-vertical-layout/style.ts
- frontend/src/components/description-modal/DescriptionModal.tsx
- frontend/src/components/description-modal/style.ts
[MAG-460](https://jira.support-ent.fr/browse/MAG-460)
> #fix(css): #MAG-460 fix vertical view + card + backgound + description modal styles

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/card-content-image-display/style.ts
> fix(card): #MAG-452 #MAG-453 fix card height and text border radius

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/drop-down-list/style.ts
- frontend/src/components/tooltip/Tooltip.tsx
- frontend/src/components/tooltip/types.ts
fix style and fix legend missing
[MAG-452](https://jira.support-ent.fr/browse/MAG-452)
> fix(card) : #MAG-452 fix style and fix legend missing

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/card-content-svg-display/CardContentSvgDisplay.tsx
- frontend/src/components/card-content-svg-display/style.ts
- frontend/src/components/card-content-svg-display/types.ts
- frontend/src/components/card-content/utils.tsx
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
fix application icons and card favorite count missing
[MAG-453](https://jira.support-ent.fr/browse/MAG-453)
> fix(card) : #MAG-469 fix application icons and card favorite count missing

- frontend/src/services/api/boardData.service.ts
fix cards in the exact inverse order
Vérifier que les cartes sont dans le même ordre que Angular, notamment sur des gros tableaux
[MAG-470](https://jira.support-ent.fr/browse/MAG-470)
> fix(cards) : #MAG-470 fix cards in the exact inverse order

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/types.ts
- frontend/src/components/cards-free-layout/CardsFreeLayout.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
fix favorites number not shown
[MAG-453](https://jira.support-ent.fr/browse/MAG-453)
> fix(favorites) : #MAG-453 fix favorites number not shown

- backend/src/main/resources/i18n/de.json
- backend/src/main/resources/i18n/en.json
- backend/src/main/resources/i18n/es.json
- backend/src/main/resources/i18n/fr.json
- backend/src/main/resources/i18n/it.json
- backend/src/main/resources/i18n/pt.json
- frontend/src/components/cards-vertical-layout/style.ts
> fix(display): #MAG-449 fix spelling + vertical sectionName width

- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/section-name/SectionName.tsx
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
> fix(readOnly): #MAG-449 fix read only rights

- frontend/src/components/card-content-svg-display/CardContentSvgDisplay.tsx
- frontend/src/components/magnets-collection/MagnetsCollectionModal.scss
- frontend/src/components/magnets-collection/MagnetsCollectionModal.tsx
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
- frontend/src/providers/SVGProvider/index.tsx
- frontend/src/providers/SVGProvider/types.ts
- frontend/src/routes/board/index.tsx
fix favorites not working and style spacing with board title
[MAG-416](https://jira.support-ent.fr/browse/MAG-416)
> fix(favorites) : #MAG-416 fix favorites not working and style

- backend/src/main/java/fr/cgi/magneto/controller/MagnetoController.java
- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
> fix(card) : fix legend not left aligned

- frontend/src/components/header-view/HeaderView.scss
> fix(header): #MAG-480 title string

- frontend/src/components/board-card/style.ts
> fix(BoardCard): #MAG-479 fix magnet type style

- .github/workflows/dev-check-repository.yml
- frontend/package.json
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/core/enums/board-modal-type.ts
- frontend/src/hooks/useSideMenuData.ts
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
- frontend/src/providers/BoardProvider/utils.ts
> feat(sideBarMenu) : #MAG-402 add board update modal

- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/components/create-magnet/style.ts
- frontend/src/components/file-picker-workspace/FilePickerWorkspace.tsx
- frontend/src/components/file-picker-workspace/style.ts
- frontend/src/components/image-container/ImageContainer.tsx
- frontend/src/components/image-container/style.ts
- frontend/src/components/image-container/types.ts
add creation of card by image on the menu (displays an image and let the user change it with MediaLibrary)
[MAG-396](https://jira.support-ent.fr/browse/MAG-396)
> feat(card) : #MAG-396 add creation of card by image

- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/components/create-magnet/utils.ts
> feat(link,sound): #MAG-398-400  createmagnet for sound & link

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/cards-vertical-layout/style.ts
- frontend/src/components/cards-vertical-layout/types.ts
- frontend/src/components/dnd-section/DndSection.tsx
- frontend/src/components/dnd-section/style.ts
- frontend/src/components/dnd-section/types.ts
- frontend/src/hooks/dnd-hooks/types.ts
- frontend/src/hooks/dnd-hooks/useSectionsDnD.ts
- frontend/src/hooks/dnd-hooks/utils.ts
- frontend/src/providers/BoardProvider/index.tsx
> feat(dnd) : #MAG-486 dnd impl vertical and horizontal

- frontend/src/components/board-create-magnet-magnet-modal/style.ts
> fix(magnetMagnetModal): #MAG-401 fix card selection

- frontend/src/components/card-content-image-display/CardContentImageDisplay.tsx
- frontend/src/components/card-content-image-display/style.ts
- frontend/src/components/card-content/utils.tsx
> fix(card) : #MAG-397 fix card content not reading local videos

- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/providers/MediaLibraryProvider/index.tsx
> fix(card-creation) : #MAG-395 fix multiple PR returns

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/card-comment/CardComment.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/cards-vertical-layout/style.ts
- frontend/src/components/cards-vertical-layout/types.ts
- frontend/src/components/dnd-section/DndSection.tsx
- frontend/src/components/dnd-section/style.ts
- frontend/src/components/section-name/SectionName.tsx
- frontend/src/hooks/dnd-hooks/customPointer.ts
- frontend/src/hooks/dnd-hooks/types.ts
- frontend/src/hooks/dnd-hooks/useSectionsDnD.ts
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
> Mag 486 anims

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-create-magnet-magnet-modal/BoardCreateMagnetMagnetModal.tsx
- frontend/src/components/board-create-magnet-magnet-modal/style.ts
- frontend/src/components/board-create-magnet-magnet-modal/useRenderContent.tsx
- frontend/src/components/tab-list/TabList.tsx
- frontend/src/components/tab-list/style.ts
- frontend/src/hooks/dnd-hooks/useFreeLayoutCardDnD.ts
> fix(magnetmagnet): fixed several style issues+addtoast

- frontend/src/components/create-magnet/CreateMagnet.tsx
> fix(link): MAG-400 fix link magnet behavior

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/section-name/SectionName.tsx
- frontend/src/hooks/useSideMenuData.ts
fix multiple rights on the folder
> fix(rights) : fix multiple rights on the folder

- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
> fix(rights): section dnd for manage right only

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/board-card/useCardDropDownItems.tsx
- frontend/src/components/board-card/useResourceTypeDisplay.ts
- frontend/src/components/cards-free-layout/CardsFreeLayout.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/cards-vertical-layout/types.ts
- frontend/src/components/section-name/SectionName.tsx
- frontend/src/components/section-name/types.ts
- frontend/src/hooks/dnd-hooks/types.ts
- frontend/src/hooks/dnd-hooks/useSectionsDnD.ts
> fix(dnd): first perf improvement

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-create-magnet-magnet-modal/useRenderContent.tsx
- frontend/src/core/constants/pointerTypes.const.ts
- frontend/src/hooks/dnd-hooks/customPointer.ts
- frontend/src/services/api/cards.service.ts
- frontend/src/services/api/empltySplitApi.service.ts
[MAG-509](https://jira.support-ent.fr/browse/MAG-509)
> feat(favorites): #MAG-509 add card favorites feature

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/board-card/useCardDropDownItems.tsx
[MAG-513](https://jira.support-ent.fr/browse/MAG-513)
> feat(lock): add lock magnet feature and right control

- frontend/src/components/board-item/BoardItem.tsx
> fix(BoardItem): #MAG-482 all item clickable

- frontend/src/components/Preview-modal/PreviewModal.tsx
- frontend/src/components/Preview-modal/style.ts
- frontend/src/components/Preview-modal/types.ts
- frontend/src/components/card-content-audio/CardContentAudio.tsx
- frontend/src/components/card-content-audio/style.ts
- frontend/src/components/card-content-audio/types.ts
- frontend/src/components/comment-panel/CommentPanel.tsx
- frontend/src/components/comment-panel/style.ts
- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/components/create-magnet/style.ts
- frontend/src/components/preview-caption-and-desc/PreviewCaptionAndDesc.tsx
- frontend/src/components/preview-caption-and-desc/style.ts
- frontend/src/components/preview-caption-and-desc/types.ts
- frontend/src/components/preview-content-image/PreviewContentImage.tsx
- frontend/src/components/preview-content-image/style.ts
- frontend/src/components/preview-content-image/types.ts
- frontend/src/components/preview-content/PreviewContent.tsx
- frontend/src/components/preview-content/utils.tsx
> feat(PreviewAudio) : reuse CardAudioContent

- frontend/src/common/ShareModal/ShareModal.tsx
- frontend/src/common/ShareModal/hooks/useSearch.tsx
- frontend/src/common/ShareModal/hooks/useShare.ts
- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/board-card/useCardDropDownItems.tsx
- frontend/src/components/board-create-magnet-magnet-modal/useRenderContent.tsx
- frontend/src/components/card-actions/CardActions.tsx
- frontend/src/components/card-actions/style.ts
- frontend/src/components/card-actions/types.ts
- frontend/src/components/card-card-content/CardCardContent.tsx
- frontend/src/components/card-card-content/style.ts
- frontend/src/components/card-card-content/types.ts
- frontend/src/components/card-comment/CardComment.tsx
- frontend/src/components/card-header/CardHeader.tsx
- frontend/src/components/card-header/style.ts
- frontend/src/components/card-header/types.ts
- frontend/src/components/card-modals/CardModals.tsx
- frontend/src/components/card-modals/types.ts
- frontend/src/components/cards-free-layout/CardsFreeLayout.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/magnets-collection/FavoriteViewByBoard.tsx
- frontend/src/components/magnets-collection/FavoriteViewByCard.tsx
- frontend/src/components/read-view/ReadView.tsx
- frontend/src/components/share-modal/ShareModalMagneto.tsx
- frontend/src/hooks/useBoardCard.ts
- frontend/src/hooks/useElapsedTime.ts
> perf(BoardView): reduce unnecessary rerenders and optimize callbacks

- frontend/src/components/card-content-file/CardContentFile.tsx
- frontend/src/hooks/useEntcoreBehaviours.ts
> fix(preview) : #MAG-505 fix lool init missing

- frontend/src/components/card-content-file/CardContentFile.tsx
- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/services/api/emptySplitWorkspace.ts
- frontend/src/services/api/workspace.service.ts
fix documents not synced when a new one is created through a new magnet + added a condition to prevent lool crashes
> fix(filesinfos) : #MAG-505 fix documents not synced

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/useCardDropDownItems.tsx
> fix(lockcard): update rights for action

- backend/src/main/resources/i18n/fr.json
- frontend/src/components/board-card/useCardDropDownItems.tsx
- frontend/src/components/card-duplicate-or-move-modal/CardDuplicateOrMove.tsx
> fix(duplicatecard): rights+i18ns

- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/board-view/style.ts
- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/components/create-magnet/style.ts
> fix(magnet) : #MAG-516 fix create/edition modal filled by other magnets

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/useCardDropDownItems.tsx
- frontend/src/hooks/useBoardCard.ts
> fix(deleMagnet): #MAG-511 update rights action

- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/components/read-view/ReadView.tsx
> fix(select): select value fixed

- frontend/src/components/board-view/style.ts
- frontend/src/components/board-view/types.ts
- frontend/src/components/file-drop-zone/style.ts
> fixed(dropZone): fixed textpopup style

- frontend/src/components/Preview-modal/PreviewModal.tsx
- frontend/src/components/Preview-modal/style.ts
- frontend/src/components/Preview-modal/types.ts
- frontend/src/components/card-content-file/CardContentFile.tsx
> fix(responsive): responsive for text

- frontend/src/components/card-content-file/CardContentFile.tsx
> fix(CSVparser): remove preview for xlsx and xls

- frontend/src/components/card-content-text/cardContentText.tsx
> fix(text): add iframe to whitelist

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/card-modals/CardModals.tsx
- frontend/src/components/card-modals/types.ts
fix magnet edit opening two modals
> fix(edit) : #MAG-510 fix magnet edit opening two modals

- frontend/src/components/create-board/CreateBoard.tsx
- frontend/src/hooks/useImageHandler.ts
> fix(createMagnet): fix imagepicker in update

- frontend/src/components/create-board/CreateBoard.tsx
- frontend/src/components/unique-image-picker/UniqueImagePicker.tsx
- frontend/src/hooks/useImageHandler.ts
- frontend/src/providers/MediaLibraryProvider/index.tsx
> fix : #MAG-473 fix multiple windows and imagepicker behaviours

- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/useCardDropDownItems.tsx
- frontend/src/hooks/useBoardCard.ts
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
> Mag 511fixrights

- frontend/src/components/card-content-file/CardContentFile.tsx
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
> fix(preview) : fix lool buttons consistency

- frontend/src/components/create-magnet/CreateMagnet.tsx
> fix(form): #MAG-510 remove section choice if edition

- frontend/package.json
- frontend/src/main.tsx
- frontend/tsconfig.json
Add learning hub theme (now CRNA)
Check if items have orange/red theme
> chore: add learning hub theme (now CRNA)

- frontend/src/components/card-content-file/CardContentFile.tsx
fix download and lool edit rights with locked cards
> fix(fileinfos) : #MAG-291 fix download and lool edit rights

- frontend/src/components/board-infos-footer/BoardInfosFooter.tsx
- frontend/src/components/card-preview-board/CardPreviewBoard.tsx
fix board magnet preview with wrong infos and button behaviour
> fix(board) : #MAG-529 fix board magnet preview with wrong infos and button behaviour

- backend/src/main/resources/i18n/fr.json
- frontend/src/components/message-modal/style.ts
- frontend/src/components/toaster-container/ToasterContainer.tsx
fix notification style and add toaster
> fix(notification) : #MAG-264 fix notification style and add toaster

- backend/src/main/java/fr/cgi/magneto/controller/BoardController.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
- backend/src/main/java/fr/cgi/magneto/service/BoardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- backend/src/main/resources/angular-dist/ts/models/board.model.ts
- backend/src/main/resources/i18n/fr.json
- backend/src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
- frontend/src/components/board-create-magnet-board-modal/BoardList.scss
- frontend/src/components/board-create-magnet-board-modal/useRenderContent.tsx
- frontend/src/components/tab-list/utils.ts
- frontend/src/hooks/useSideMenuData.ts
- frontend/src/models/board.model.ts
- frontend/src/services/api/boards.service.ts
> fix(board) : #MAG-527 fix board magnet returns

- backend/src/main/resources/i18n/timeline/fr.json
- backend/src/main/resources/notify/notify_board.html
- frontend/src/components/toaster-container/ToasterContainer.tsx
fix notification punctuation having an extra space and condition of the button appearing when notif can't be sent (board isnt shared)
> fix(notification) : #MAG-264 fix notification style and condition

- backend/src/main/java/fr/cgi/magneto/model/boards/Board.java
> fix(preview) : #MAG-529 fix wrong magnet count for free boards

- frontend/src/components/app-view/index.scss
- frontend/src/components/create-board/CreateBoard.tsx
> fix(medialibrary) : #MAG-531 fix MediaLibrary style in parameters

- backend/src/main/java/fr/cgi/magneto/controller/CardController.java
- backend/src/main/java/fr/cgi/magneto/model/cards/CardPayload.java
- backend/src/main/java/fr/cgi/magneto/service/CardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultSectionService.java
- frontend/src/components/board-card/BoardCard.tsx
- frontend/src/components/board-card/style.ts
- frontend/src/components/cards-free-layout/CardsFreeLayout.tsx
- frontend/src/components/cards-horizontal-layout/CardsHorizontalLayout.tsx
- frontend/src/components/cards-vertical-layout/CardsVerticalLayout.tsx
- frontend/src/components/drop-down-list/DropDownList.tsx
- frontend/src/components/tooltip/Tooltip.tsx
- frontend/src/components/tooltip/types.ts
- frontend/src/hooks/dnd-hooks/reorderUtils.ts
- frontend/src/hooks/dnd-hooks/useFreeLayoutCardDnD.ts
- frontend/src/hooks/dnd-hooks/useSectionsDnD.ts
Fix all the back actions (delete, add, move, ...)
> fix(dnd) : #MAG-199 fix multiple locked cards behaviours

- backend/pom.xml
- backend/src/main/java/fr/cgi/magneto/controller/ExportController.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Slideshow.java
- backend/src/main/java/fr/cgi/magneto/factory/SlideFactory.java
- backend/src/main/java/fr/cgi/magneto/helper/SlideHelper.java
- backend/src/main/java/fr/cgi/magneto/model/properties/SlideProperties.java
- backend/src/main/java/fr/cgi/magneto/model/slides/Slide.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideBoard.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideDescription.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideFile.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideLink.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideMedia.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideText.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideTitle.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
- backend/src/main/resources/img/audio_icon.svg
- Addition of new dependencies in the pom.xml file for poi-ooxml-full.
- Modifications in ExportController.java with additional imports and debug prints.
- Addition of the CONTENTTYPE constant in Field.java.
- Addition of several constants in Slideshow.java for content type support.
- Changes in SlideFactory.java to use contentType instead of extension.
- Addition of new methods and imports in SlideHelper.java to handle media.
- Changes in SlideProperties.java to use contentType instead of extension.
- Modifications in slide model classes (Slide, SlideBoard, SlideDescription, SlideFile, SlideLink, SlideMedia, SlideText, SlideTitle) to use XSLFSlide and contentType.
- Revisions in DefaultExportService.java to support new content types and slides.
-media video
-media son …
> feat(slideMedia): #MAG-548 slide media integration

- backend/src/main/java/fr/cgi/magneto/core/constants/Slideshow.java
- backend/src/main/java/fr/cgi/magneto/factory/SlideFactory.java
- backend/src/main/java/fr/cgi/magneto/helper/SlideHelper.java
- backend/src/main/java/fr/cgi/magneto/model/properties/SlideProperties.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideLink.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
- backend/src/main/resources/img/extension/audio.svg
- backend/src/main/resources/img/extension/default.svg
- backend/src/main/resources/img/extension/file.svg
- backend/src/main/resources/img/extension/image.svg
- backend/src/main/resources/img/extension/link.svg
- backend/src/main/resources/img/extension/pdf.svg
- backend/src/main/resources/img/extension/sheet.svg
- backend/src/main/resources/img/extension/text.svg
- backend/src/main/resources/img/extension/video.svg
add link slides with title, description, the link SVG and the url
[MAG-546](https://jira.support-ent.fr/browse/MAG-546)
> feat(slides) : #MAG-546 add link slides

- backend/src/main/java/fr/cgi/magneto/controller/ExportController.java
- backend/src/main/java/fr/cgi/magneto/service/ExportService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
add archive with slideshow and its documents
[MAG-554](https://jira.support-ent.fr/browse/MAG-554)
> feat(slides) : #MAG-554 add archive with slideshow and its documents

- backend/src/main/java/fr/cgi/magneto/core/constants/Slideshow.java
- backend/src/main/java/fr/cgi/magneto/helper/SlideHelper.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideBoard.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideText.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
- backend/src/main/resources/i18n/en.json
- backend/src/main/resources/i18n/fr.json
- frontend/src/components/export-modal/ExportModal.tsx
- frontend/src/components/export-modal/style.ts
> Mag 212fixes

- backend/src/main/java/fr/cgi/magneto/controller/BoardController.java
- backend/src/main/java/fr/cgi/magneto/controller/CardController.java
- backend/src/main/java/fr/cgi/magneto/controller/SectionController.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
- backend/src/main/java/fr/cgi/magneto/core/enums/EventBusActions.java
- backend/src/main/java/fr/cgi/magneto/model/boards/Board.java
- backend/src/main/java/fr/cgi/magneto/model/boards/BoardPayload.java
- backend/src/main/java/fr/cgi/magneto/service/BoardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- backend/src/main/resources/jsonschema/board.json
- backend/src/main/resources/jsonschema/boardUpdate.json
- backend/src/test/java/fr/cgi/magneto/model/BoardPayloadTest.java
- backend/src/test/java/fr/cgi/magneto/model/BoardTest.java
add public routes and board + document visibility switching API 
[MAG-558](https://jira.support-ent.fr/browse/MAG-558)
[MAG-562](https://jira.support-ent.fr/browse/MAG-562)
> feat(visibility) : #MAG-558 add public routes and board + document visibility switching API 

- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- backend/src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
- frontend/src/app/root/index.tsx
- frontend/src/common/ShareModal/ShareModal.tsx
- frontend/src/common/ShareModal/utils/utils.ts
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/card-content-audio/CardContentAudio.tsx
- frontend/src/components/card-content-file/CardContentFile.tsx
- frontend/src/components/card-content/utils.tsx
- frontend/src/components/csv-viewer/CSVViewer.tsx
- frontend/src/components/header-view/HeaderView.tsx
- frontend/src/components/preview-content/utils.tsx
- frontend/src/components/public-layout/PublicLayout.tsx
- frontend/src/components/read-view/ReadView.tsx
- frontend/src/core/constants/roots.const.ts
- frontend/src/main.tsx
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/providers/BoardProvider/types.ts
- frontend/src/routes/read-public/index.tsx
add read view, polish a lot of the style and public doc behaviours with booleans and lot of tiny managing.
[MAG-560](https://jira.support-ent.fr/browse/MAG-560)
> feat(public) : #MAG-560 add read view and public doc behaviours

- backend/src/main/java/fr/cgi/magneto/controller/ExportController.java
- backend/src/main/java/fr/cgi/magneto/model/properties/SlideProperties.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
- backend/src/main/resources/img/magneto.svg
fix export rights
Check export with API directly for different rights. read shouldnt work, all others should.
[MAG-556](https://jira.support-ent.fr/browse/MAG-556)
> fix(export) : #MAG-556 fix export rights

- backend/deployment/magneto/conf.json.template
- backend/src/main/java/fr/cgi/magneto/config/MagnetoConfig.java
- backend/src/main/java/fr/cgi/magneto/controller/MagnetoController.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
- backend/src/main/java/fr/cgi/magneto/helper/SlideHelper.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideBoard.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideMedia.java
- backend/src/main/java/fr/cgi/magneto/model/slides/SlideTitle.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultExportService.java
- frontend/index.html
- frontend/src/core/constants/preferences.const.ts
- frontend/src/main.tsx
> fix(magneto) : #MAG-557 fix multiple issues for export and libui config

- frontend/src/components/cards-vertical-layout/style.ts
- frontend/src/components/dnd-section/DndSection.tsx
fix cursor with sections dnd
[MAG-499](https://jira.support-ent.fr/browse/MAG-499)
> fix(dnd) : #MAG-499 fix cursor with sections dnd

- JenkinsFile
- backend/src/main/java/fr/cgi/magneto/controller/BoardController.java
- backend/src/main/java/fr/cgi/magneto/controller/FakeRight.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Rights.java
- backend/src/main/java/fr/cgi/magneto/security/PublicBoardRight.java
- frontend/src/common/ShareModal/ShareModal.tsx
- frontend/src/config/index.ts
- frontend/src/services/queries/index.ts
add workflow right for public board activation
Check the API and the front if they both work correctly around the new right (which should be checked in the admin console)
[MAG-568](https://jira.support-ent.fr/browse/MAG-568)
> feat(section) : #MAG-568 add workflow right for public board activation

- backend/src/main/java/fr/cgi/magneto/model/boards/Board.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultSectionService.java
fix delete sections changing their order
Check that section actions are still fine, particulary deleting, and check the order everytime
[MAG-542](https://jira.support-ent.fr/browse/MAG-542)
> fix(section) : #MAG-542 fix delete sections changing their order

- frontend/src/components/board-create-magnet-magnet-modal/BoardCreateMagnetMagnetModal.tsx
- frontend/src/components/board-create-magnet-magnet-modal/style.ts
- frontend/src/components/tab-list/TabList.tsx
- frontend/src/components/tab-list/style.ts
improve responsive and switch display
Check the Card modal creation and check the responsive + switch display on favorite tab + favorite display on stars
[MAG-498](https://jira.support-ent.fr/browse/MAG-498)
> feat(create-card) : #MAG-498 improve responsive and switch display

- frontend/src/components/app-icon/AppIcon.tsx
- frontend/src/components/card-content-svg-display/CardContentSvgDisplay.tsx
- frontend/src/components/card-content-svg-display/style.ts
- frontend/src/components/image/Image.tsx
fix icons and placeholder for link cards
[MAG-541](https://jira.support-ent.fr/browse/MAG-541)
> fix(cards) : #MAG-541 fix icons and placeholder for link cards

- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultWorkspaceService.java
fix duplication occuring in workspace because of document having its isShared changed to true
[MAG-377](https://jira.support-ent.fr/browse/MAG-377)
> fix(documents) : #MAG-377 fix duplication occuring in workspace

- backend/src/main/java/fr/cgi/magneto/controller/FolderController.java
- backend/src/main/java/fr/cgi/magneto/service/FolderService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
fix folders renaming for not-owner managers
[MAG-445](https://jira.support-ent.fr/browse/MAG-445)
> fix(folders) : #MAG-445 fix folders renaming for not-owner managers

- backend/src/main/java/fr/cgi/magneto/controller/MagnetoCollaborationController.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
- backend/src/main/java/fr/cgi/magneto/helper/MagnetoMessage.java
- backend/src/main/java/fr/cgi/magneto/model/boards/Board.java
- backend/src/main/java/fr/cgi/magneto/model/cards/Card.java
- backend/src/main/java/fr/cgi/magneto/service/MagnetoCollaborationService.java
- backend/src/main/java/fr/cgi/magneto/service/ServiceFactory.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultMagnetoCollaborationService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/MagnetoMessageFactory.java
- backend/src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
- backend/src/test/java/fr/cgi/magneto/service/CardServiceTest.java
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/services/api/boardData.service.ts
- frontend/src/services/websocket/useWebSocketManager.ts
Add creation of card with a message sent by socket
[MAG-581](https://jira.support-ent.fr/browse/MAG-581)
> feat(synchron) : #MAG-581 add creation of card by socket

- backend/src/main/java/fr/cgi/magneto/core/enums/MagnetoMessageType.java
- backend/src/main/java/fr/cgi/magneto/core/events/MagnetoUserAction.java
- backend/src/main/java/fr/cgi/magneto/model/cards/CardPayload.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultMagnetoCollaborationService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/MagnetoMessageFactory.java
- frontend/src/components/board-view/BoardView.tsx
- frontend/src/components/create-magnet/CreateMagnet.tsx
- frontend/src/providers/BoardProvider/index.tsx
- frontend/src/services/api/boardData.service.ts
- frontend/src/services/websocket/useWebSocketManager.ts
add board update in synchron mode
> feat(synchron) : #MAG-583 add board update in synchron mode

- backend/src/main/java/fr/cgi/magneto/controller/CardController.java
- backend/src/main/java/fr/cgi/magneto/controller/MagnetoCollaborationController.java
- backend/src/main/java/fr/cgi/magneto/core/enums/MagnetoMessageType.java
- backend/src/main/java/fr/cgi/magneto/core/events/MagnetoUserAction.java
- backend/src/main/java/fr/cgi/magneto/helper/MagnetoMessage.java
- backend/src/main/java/fr/cgi/magneto/service/CardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultMagnetoCollaborationService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/MagnetoMessageFactory.java
- backend/src/test/java/fr/cgi/magneto/model/CardPayloadTest.java
- frontend/src/hooks/useBoardCard.ts
- frontend/src/services/websocket/useWebSocketManager.ts
add favorites to synchron
[MAG-585](https://jira.support-ent.fr/browse/MAG-585)
> feat(synchron) : #MAG-585 add favorites to synchron

- backend/src/main/java/fr/cgi/magneto/core/events/MagnetoUserAction.java
- backend/src/main/java/fr/cgi/magneto/model/boards/Board.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultMagnetoCollaborationService.java
- backend/src/main/java/fr/cgi/magneto/service/impl/MagnetoMessageFactory.java
- frontend/src/components/card-duplicate-or-move-modal/CardDuplicateOrMove.tsx
- frontend/src/core/enums/websocket-message-type.ts
- frontend/src/hooks/dnd-hooks/useFreeLayoutCardDnD.ts
- frontend/src/hooks/dnd-hooks/useSectionsDnD.ts
- frontend/src/hooks/useApplyBoardUpdate.ts
add cards DnD in synchron mode (both free and sections modes)
[MAG-587](https://jira.support-ent.fr/browse/MAG-587)
> feat(synchron) : #MAG-587 add cards DnD in synchron mode

- backend/src/main/java/fr/cgi/magneto/controller/MagnetoCollaborationController.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
- backend/src/main/java/fr/cgi/magneto/core/enums/UserColor.java
- backend/src/main/java/fr/cgi/magneto/core/events/CollaborationUsersMetadata.java
- backend/src/main/java/fr/cgi/magneto/helper/MagnetoMessage.java
- backend/src/main/java/fr/cgi/magneto/model/cards/Card.java
- backend/src/main/java/fr/cgi/magneto/model/cards/CardPayload.java
- backend/src/main/java/fr/cgi/magneto/model/user/User.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultMagnetoCollaborationService.java
- frontend/src/components/connected-users-chip/ConnectedUsersChip.tsx
- frontend/src/components/connected-users-chip/style.ts
- frontend/src/components/header-view/style.ts
- frontend/src/hooks/useBoardCard.ts
- frontend/src/providers/WebsocketProvider/index.tsx
- frontend/src/providers/WebsocketProvider/types.ts
fix favorites not working because of previous changes (now the button only changes for the user doing the action)
fix user list style and adds color borders
[MAG-15](https://jira.support-ent.fr/browse/MAG-15)
> fix(synchron) : #MAG-15 fix favorites and user list

- backend/src/main/java/fr/cgi/magneto/controller/BoardController.java
- backend/src/main/java/fr/cgi/magneto/controller/ShareBoardController.java
- backend/src/main/java/fr/cgi/magneto/core/constants/Field.java
fix email notifications not redirecting to magneto URL (missed scheme + host)
check if all email notification now have the entire URL
[MAG-590](https://jira.support-ent.fr/browse/MAG-590)
> fix(notif) : #MAG-590 fix email notifications not redirecting to magneto

- frontend/src/components/connected-users-chip/ConnectedUsersChip.tsx
- frontend/src/components/user-avatar/UserAvatar.tsx
- frontend/src/core/enums/MUI-constants.enum.ts
- frontend/src/hooks/useInitials.ts
- frontend/src/routes/board/index.tsx
- frontend/src/services/api/directory.service.ts
- frontend/src/services/api/emptySplitDirectory.ts
- frontend/src/store.ts
fix user list initials mixing with default icon (weird look) + externalize user icons
[MAG-571](https://jira.support-ent.fr/browse/MAG-571)
> fix(synchron) ; #MAG-571 fix user list initials mixing with default icon

- backend/src/main/java/fr/cgi/magneto/Magneto.java
- backend/src/main/java/fr/cgi/magneto/realtime/CollaborationController.java
- backend/src/main/java/fr/cgi/magneto/realtime/DefaultMagnetoCollaborationService.java
- backend/src/main/java/fr/cgi/magneto/realtime/MagnetoMessageType.java
- backend/src/main/java/fr/cgi/magneto/realtime/events/CardEditingInformation.java
- backend/src/main/java/fr/cgi/magneto/realtime/events/MagnetoUserAction.java
- backend/src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
- backend/src/main/resources/i18n/fr.json
- frontend/package.json
- frontend/src/core/constants/toast-config.const.ts
- frontend/src/core/enums/websocket-message-type.ts
- frontend/src/hooks/dnd-hooks/useSectionsDnD.ts
- frontend/src/hooks/useBoardCard.ts
- frontend/src/main.tsx
- frontend/src/providers/WebsocketProvider/index.tsx
fix multiple redis issues and adds QoL (disconnection while afk, better fluidity and stability, ...)
> fix(synchron) : #MAG-612 fix multiple redis issues
